# -*- coding: utf-8 -*-
"""Pin the ONE coordinate conversion in the driver, by running the shipped bytes.

THE DEFECT THIS EXISTS FOR.  Browser-side, AbsolutePosition is GUI space: its y
is measured below the topbar.  VirtualInputManager, and UIS:GetMouseLocation(),
are SCREEN space: their y includes it.  On this client the two differ by 58 px.
Every synthetic press the driver made before tag d5 therefore landed 58 px above
its target -- and NOTHING SAID SO.  SendMouseMoveEvent returned, the button
event returned, and the click went to whatever else was at that pixel.  For
clickPoint itself the symptom was absent entirely: it returned two numbers, and
they were plausible numbers, just in the wrong space.

That is the §0.18 family in its purest form -- a wrong ruler does not error, it
quietly hands you a value -- so the conversion is pinned by a test that has to
be shown CAPABLE of failing.  _tools/selftest_drive_clickpoint.py breaks it one
way per mutant and requires the matching case, and only that case, to turn red.

WHY A STUB AND NOT THE GAME.  This file can be run any number of times, and the
alternative -- measuring in the live client -- costs a shift the operator can
only start once.  The stub's job is to reproduce the MEASURED behaviour, not a
convenient one: the inset is 58 because that is what was read, and a mock that
answered nil would let a wrong reader pass here and die in the game.

WHY THE SUBJECT IS EXTRACTED BY TEXT.  This is the recorder suites' contract.
A re-typed copy of clickPoint would keep passing after the shipped one changed,
which is exactly the drift the file is here to catch.

Run:  python _tools/build_drive_clickpoint_test.py [source.luau] [out.luau]
The two path arguments exist so selftest_drive_clickpoint.py can point this SAME
extraction at a deliberately broken copy.  A mutation run through a second
builder would be testing the builder.
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
DRIVE = ROOT / "TRG_original_drive.luau"
OUT = ROOT / "_drive_clickpoint_states.luau"

HEAD = """--!nocheck
-- GENERATED by _tools/build_drive_clickpoint_test.py -- edit that file, not this one.
-- clickPoint() below is EXTRACTED from _tools/TRG_original_drive.luau by text and run
-- under a stub engine.  No Roblox API is touched; see the builder for why.

local results = {}
local function say(s) results[#results + 1] = tostring(s) end

local function check(name, got, want)
  local ok = (got == want)
  say((ok and 'PASS ' or 'FAIL ') .. name)
  if not ok then
    say('     got  [' .. tostring(got) .. ']')
    say('     want [' .. tostring(want) .. ']')
  end
end

-- ============================== STUB ENGINE ===============================
-- Vector2 needs __add, __sub and __div here.  The subject adds a point to a
-- point, divides a size by a scalar, and -- the mutation that found this --
-- subtracts.  Under Lua 5.1 each of those is a metatable arm, and a stub missing
-- one does not fail a CHECK: it raises, the whole harness aborts, and the run is
-- red for a reason that has nothing to do with the conversion.  That is a red
-- for the wrong reason, which is worse than the worst kind of green, because it
-- cannot be told from a real catch.  __sub is here because the SUBTRACT mutation
-- demonstrated its absence, not because the current subject uses it.
local Vector2 = {}
Vector2.__index = Vector2
Vector2.__add = function(a, b) return Vector2.new(a.X + b.X, a.Y + b.Y) end
Vector2.__sub = function(a, b) return Vector2.new(a.X - b.X, a.Y - b.Y) end
Vector2.__div = function(a, b) return Vector2.new(a.X / b, a.Y / b) end
function Vector2.new(x, y) return setmetatable({ X = x, Y = y }, Vector2) end

-- The inset is a VARIABLE, not the constant 58.  A subject that hardwires 58
-- passes every case measured on this client and is still wrong the moment the
-- topbar is a different height, so one case below runs at 36 px and another at
-- an X of 4 purely so that hardwiring either component goes red.
local INSET = { X = 0, Y = 58 }

local GuiService = {}
function GuiService:GetGuiInset() return Vector2.new(INSET.X, INSET.Y) end

local game = {}
function game:GetService(name)
  if name == 'GuiService' then return GuiService end
  error('unexpected service: ' .. tostring(name))
end

-- A LayerCollector.  `ignore` is nil when the class simply has no such property,
-- false for a ScreenGui that does not set it, and true for one that does.  Three
-- states, because the subject has to tell the middle one from the other two.
local function makeLC(className, ignore)
  local lc = { ClassName = className }
  if ignore ~= nil then lc.IgnoreGuiInset = ignore end
  function lc:IsA(c) return c == self.ClassName end
  return lc
end

-- A LayerCollector that REFUSES the flag, the way a real one whose class never
-- had the property does.  The subject pcalls that read, and a pcall is only
-- proven to be doing work if something in this file actually raises inside it.
local function makeLCNoFlag(className)
  local lc = { ClassName = className }
  function lc:IsA(c) return c == self.ClassName end
  return setmetatable(lc, { __index = function(_, k)
    if k == 'IgnoreGuiInset' then error('IgnoreGuiInset is not a valid member', 2) end
    return nil
  end })
end

local function makeBtn(ap, asSize, lc)
  local b = { AbsolutePosition = ap, AbsoluteSize = asSize, _lc = lc }
  function b:FindFirstAncestorWhichIsA(c)
    if c ~= 'LayerCollector' then return nil end
    return self._lc
  end
  return b
end

-- A button whose named property RAISES when read, the way AbsolutePosition does
-- on something that is not a GuiObject at all.  The raising field is deliberately
-- absent from the table: a raw field would shadow __index and nothing would raise.
local function makeRaisingBtn(which)
  local b = {}
  function b:FindFirstAncestorWhichIsA(c) return nil end
  return setmetatable(b, { __index = function(_, k)
    if k == which then error(k .. ' is not a valid member', 2) end
    if k == 'AbsolutePosition' then return Vector2.new(0, 0) end
    if k == 'AbsoluteSize' then return Vector2.new(0, 0) end
    return nil
  end })
end
"""

TAIL = """
-- ================================= CASES ==================================
-- Observed is a STRING carrying both halves: the point, and the NAME of the space
-- it was computed in.  The name is not decoration.  'nospace' is what an unknown
-- ancestry produces, and a run that prints it has measured nothing even though it
-- printed two perfectly plausible numbers -- which is the whole history of this
-- function.  The format is %.6f, not %.0f: rounding for display would hide the
-- missing floor (C10) behind the same four digits.
local function observe(btn)
  local p, _, space = clickPoint(btn)
  if p == nil then return '(nil) ' .. tostring(space) end
  return string.format('%.6f,%.6f', p.X, p.Y) .. ' ' .. tostring(space)
end

local function run(name, btn, want) check(name, observe(btn), want) end

local SG   = makeLC('ScreenGui', nil)    -- the flag is absent on the instance
local SGF  = makeLC('ScreenGui', false)  -- the flag is set, to false
local SGT  = makeLC('ScreenGui', true)   -- the flag is set, to true
local SURF = makeLC('SurfaceGui', nil)   -- a LayerCollector, but not a screen
local SGX  = makeLCNoFlag('ScreenGui')   -- the pcall's reason to exist

-- 447,566 is the report screen's PostShiftButton rounded up to whole pixels:
-- the live read was 446.600,566.400 with size 60x60.  So it is the real button,
-- but it is NOT the live number verbatim -- whole pixels are chosen here so the
-- expected strings below are exact, and the flooring the subject does is
-- exercised on its own by C10.
run('C1 a ScreenGui that does not ignore the inset has the inset ADDED',
  makeBtn(Vector2.new(447, 566), Vector2.new(60, 60), SG),
  '477.000000,654.000000 inset+0,58')

-- C2 is the case d5 got wrong, and the whole reason d6 exists.  d5 read
-- IgnoreGuiInset as "these children are already in screen space" and returned
-- 596 here.  The live button sits at 672, not 614, so 596 was 58 px short -- and
-- note the expected string: the NUMBER is identical to C1's.  The flag does not
-- move the point; it only appends a word to the NAME.  A future reader who sees
-- '/ignoreinset' and reaches for the inset must be able to tell from this file
-- that the label moved and the coordinate did not.
run('C2 a ScreenGui with IgnoreGuiInset gets the SAME inset -- the flag labels, it does not branch',
  makeBtn(Vector2.new(447, 566), Vector2.new(60, 60), SGT),
  '477.000000,654.000000 inset+0,58/ignoreinset')

-- C12 pins the other half of that: false and absent must be indistinguishable.
-- If a future edit made `false` add a suffix too, C2 alone would stay green.
run('C12 the flag at false is not the flag at true -- no suffix, same point',
  makeBtn(Vector2.new(447, 566), Vector2.new(60, 60), SGF),
  '477.000000,654.000000 inset+0,58')

-- C3: a SurfaceGui is not a screen space at all.  Its children are laid out on
-- the surface, so no screen coordinate reaches them -- which is why the label
-- says 'layout/' rather than 'screen/'.  The point is still returned (a refusal
-- would be silently absent, which is worse than silently wrong) but the name is
-- the disclosure that the number is not a screen coordinate.
run('C3 a SurfaceGui is a LAYOUT, not a screen space, and the name says so',
  makeBtn(Vector2.new(447, 566), Vector2.new(60, 60), SURF),
  '477.000000,596.000000 layout/SurfaceGui')

run('C4 no LayerCollector ancestor is NAMED, not silently assumed to need nothing',
  makeBtn(Vector2.new(447, 566), Vector2.new(60, 60), nil),
  '477.000000,596.000000 nospace')

run('C5 a position that raises is not a rect',
  makeRaisingBtn('AbsolutePosition'), '(nil) norect')

run('C6 a size that raises is not a rect',
  makeRaisingBtn('AbsoluteSize'), '(nil) norect')

run('C7 a size of nil is not a rect',
  makeBtn(Vector2.new(447, 566), nil, SG), '(nil) norect')

-- C8 and C11 are the two that a hardwired 58 cannot pass.  An inset of 36 is not
-- a number this client ever produced; it is here so that "read it" and "remember
-- it" cannot both be green.
INSET.Y = 36
run('C8 the inset is READ, not the constant this client happens to have',
  makeBtn(Vector2.new(447, 566), Vector2.new(60, 60), SG),
  '477.000000,632.000000 inset+0,36')
INSET.Y = 58

run('C9 a flag that RAISES when read is still pressable -- the inset never depended on it',
  makeBtn(Vector2.new(447, 566), Vector2.new(60, 60), SGX),
  '477.000000,654.000000 inset+0,58')

-- 447.9 + 30 = 477.9 and 566.9 + 30 + 58 = 654.9: floor must give 477 and 654,
-- while round would give 478 and 655.  A pixel is a pixel; a half one is not.
run('C10 a fractional rect is FLOORED, not rounded',
  makeBtn(Vector2.new(447.9, 566.9), Vector2.new(60, 60), SG),
  '477.000000,654.000000 inset+0,58')

INSET.X = 4
run('C11 the inset is a POINT, not a y-offset',
  makeBtn(Vector2.new(447, 566), Vector2.new(60, 60), SG),
  '481.000000,654.000000 inset+4,58')
INSET.X = 0

-- Printed ALWAYS, green included.  `return report` alone would look identical on
-- a green run and a harness that never ran: this file is executed as a script, and
-- a top-level return is discarded, so the selftest would have had nothing to read
-- and could not tell "all green" from "the harness printed nothing".
local report = table.concat(results, string.char(10))
io.write(report .. string.char(10))
if string.find(report, 'FAIL', 1, true) ~= nil then
  os.exit(1)
end
return report
"""


def extract_click_point(src):
    m = re.search(r"^local function clickPoint\(btn\)\n.*?^end$", src, re.S | re.M)
    if m is None:
        sys.exit("clickPoint is not in the source any more -- is it still a "
                 "top-level `local function clickPoint(btn)` ending in `end` at "
                 "column 0?")
    return m.group(0)


def main(argv):
    src_path = Path(argv[1]) if len(argv) > 1 else DRIVE
    out_path = Path(argv[2]) if len(argv) > 2 else OUT
    src = src_path.read_text(encoding="utf-8")

    for needle in ("local function clickPoint(btn)",
                   "IgnoreGuiInset",
                   "GetGuiInset",
                   "FindFirstAncestorWhichIsA"):
        if needle not in src:
            sys.exit("the driver no longer contains %r -- this harness would be "
                     "testing a function that is not there" % needle)

    # The invariant, stated where it can be enforced: the rect-to-centre division
    # lives in ONE place, and both things that need a pressable point ask that one
    # place.  Re-deriving it at a call site is the original bug, so a call site
    # that grew its own copy has to fail the build rather than be missed.
    divisions = src.count("as / 2")
    if divisions != 1:
        sys.exit("the rect-to-centre division must live in exactly one place; "
                 "found %d" % divisions)
    callers = re.findall(r"= clickPoint\(", src)
    if len(callers) != 2:
        sys.exit("clickPoint must have exactly two callers (guiCensus and "
                 "pressAt); found %d" % len(callers))

    fn = extract_click_point(src)

    body = HEAD + "\n" + fn + "\n" + TAIL
    out_path.write_text(body, encoding="utf-8", newline="\n")

    raw = out_path.read_bytes()
    checks = body.count("run('C")
    print("wrote %s" % out_path.name)
    print("lines %d  bytes %d" % (body.count("\n") + 1, len(raw)))
    print("extracted clickPoint: %d line(s)" % fn.count("\n"))
    print("cases %d" % checks)
    print("backslash bytes %d  (must be 0: the editor decodes escapes once)"
          % raw.count(b"\\"))
    print("crlf bytes %d" % raw.count(b"\r\n"))
    if raw.count(b"\\") != 0:
        sys.exit("the generated harness contains a backslash byte")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
