"""Prove the player-GUI reader, which is the one reader no other test can reach.

Everything else in the recorder points at Workspace, and Workspace is the same
object for the server and for every client. PlayerGui is not: it exists only in
the client that owns it and nothing about it replicates, so this reader can only
ever run inside an injected script -- which means it gets one shot per shift and
no second attempt to notice it was wrong.

There are three ways for it to be wrong and only one of them is loud:

  * It reads the wrong property. Measured in Studio on 2026-09-27: ScreenGui
    answers Enabled and THROWS on Visible, Frame answers Visible and THROWS on
    Enabled, and no class answers both. Asking the wrong one raises, readGui
    raises with it, pollOnce raises, and the run records NOTHING -- for the whole
    shift, from a subsystem that was supposed to be additive.
  * It records the recorder. The panel this script builds is parented to
    PlayerGui and rewrites its text four times a second. A chatter guard would
    eventually condemn it, so the file would carry a NOISY verdict about a label
    the recorder owns. Silent, and it looks like a finding about the game.
  * It reads the object's own flag and calls it what the player can see. That is
    deliberate and is argued in the source; the ScreenGui's Enabled is what
    closes the gap, so this harness pins Enabled as well.

So the objects here are mocked with the MEASURED behaviour, not a convenient
one: Visible and Enabled are not fields but metatable arms that raise when asked
for on the wrong class, exactly as the engine does. A mock that answered nil
instead would let a wrong reader pass this file and die in the game.

Both regions and `keyForLabel` are EXTRACTED from the shipped recorder by text.
Nothing is re-declared here, because a harness that agrees with its own copy of
the state proves nothing about the state that ships.

    python _tools/build_gui_test.py
    /d/Lua/5.1/lua.exe -e "print(assert(loadfile('_tools/_gui_states.luau'))())"
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
RECORDER = ROOT / "TRG_original_recorder.luau"
OUT = ROOT / "_gui_states.luau"

HEAD = """--!nocheck
-- GENERATED by _tools/build_gui_test.py -- edit that file, not this one.
--
-- The two player-GUI regions and `keyForLabel` are EXTRACTED from
-- _tools/TRG_original_recorder.luau and run against a mock PlayerGui tree.
-- No Roblox API is touched.

local results = {}
local function say(s) results[#results + 1] = tostring(s) end

local function check(name, got, want)
\tlocal ok = (got == want)
\tsay((ok and 'PASS ' or 'FAIL ') .. name)
\tif not ok then
\t\tsay('     got  [' .. tostring(got) .. ']')
\t\tsay('     want [' .. tostring(want) .. ']')
\tend
end

local function checkTrue(name, cond, why)
\tsay((cond and 'PASS ' or 'FAIL ') .. name)
\tif not cond then say('     ' .. tostring(why or 'no reason given')) end
end

-- ========================== MOCK ENGINE ===================================
-- The class map is the one measured in Studio, including the part that matters
-- most: which of the two flags a class REFUSES to answer.
local ISA = {
\tScreenGui    = { ScreenGui = true, LayerCollector = true, GuiBase2d = true },
\tSurfaceGui   = { SurfaceGui = true, LayerCollector = true, GuiBase2d = true },
\tFrame        = { Frame = true, GuiObject = true, GuiBase2d = true },
\tTextLabel    = { TextLabel = true, GuiObject = true, GuiBase2d = true },
\tTextButton   = { TextButton = true, GuiObject = true, GuiBase2d = true },
\tTextBox      = { TextBox = true, GuiObject = true, GuiBase2d = true },
\tImageLabel   = { ImageLabel = true, GuiObject = true, GuiBase2d = true },
\t-- Neither flag, and it still claims to be a GuiObject. This is the class that
\t-- the class-name test would have got wrong and the probe gets right.
\tBizarreGui   = { BizarreGui = true, GuiObject = true, GuiBase2d = true },
\tFolder       = { Folder = true },
\tUIListLayout = { UIListLayout = true },
}

local function isa(class, want)
\tlocal t = ISA[class]
\tif t ~= nil and t[want] == true then return true end
\treturn class == want
end

local Signal = {}
Signal.__index = Signal
function Signal.new() return setmetatable({ _fns = {} }, Signal) end
function Signal:Connect(f) self._fns[#self._fns + 1] = f end
function Signal:Fire(...)
\tfor i = 1, #self._fns do self._fns[i](...) end
end

local Inst = {}

-- How many property reads the mock was actually asked for.  The
-- reader runs four times a second, so its price is a property of the
-- shipped design and not a matter of taste -- and it is COUNTED here
-- rather than timed, because a timing taken on a mock measures the mock.
FLAG_READS = 0

local function err(what, class)
\terror(what .. ' is not a valid member of ' .. class, 2)
end

Inst.__index = function(self, k)
\tlocal raw = rawget(self, k)
\tif raw ~= nil then return raw end
\tif k == 'Visible' then
\t\tFLAG_READS = FLAG_READS + 1
\t\tif isa(self.ClassName, 'LayerCollector') or self.ClassName == 'BizarreGui' then
\t\t\terr('Visible', self.ClassName)
\t\tend
\t\treturn self._visible
\telseif k == 'Enabled' then
\t\tFLAG_READS = FLAG_READS + 1
\t\tif not isa(self.ClassName, 'LayerCollector') or self.ClassName == 'BizarreGui' then
\t\t\terr('Enabled', self.ClassName)
\t\tend
\t\treturn self._enabled
\telseif k == 'DescendantAdded' or k == 'DescendantRemoving' then
\t\tlocal s = Signal.new()
\t\trawset(self, k, s)
\t\treturn s
\tend
\treturn Inst[k]
end

local function new(class, name)
\treturn setmetatable({
\t\tClassName = class, Name = name,
\t\t_kids = {}, _visible = true, _enabled = true,
\t}, Inst)
end

function Inst:IsA(c) return isa(self.ClassName, c) end

function Inst:GetChildren()
\tlocal t = {}
\tfor i = 1, #self._kids do t[i] = self._kids[i] end
\treturn t
end

function Inst:GetDescendants()
\tlocal t = {}
\tlocal function walk(n)
\t\tfor i = 1, #n._kids do
\t\t\tt[#t + 1] = n._kids[i]
\t\t\twalk(n._kids[i])
\t\tend
\tend
\twalk(self)
\treturn t
end

function Inst:GetFullName()
\tlocal parts, n = {}, self
\twhile n ~= nil do
\t\ttable.insert(parts, 1, n.Name)
\t\tn = n.Parent
\tend
\treturn table.concat(parts, '.')
end

function Inst:FindFirstChild(n)
\tfor i = 1, #self._kids do
\t\tif self._kids[i].Name == n then return self._kids[i] end
\tend
\treturn nil
end

function Inst:IsDescendantOf(o)
\tlocal n = self.Parent
\twhile n ~= nil do
\t\tif n == o then return true end
\t\tn = n.Parent
\tend
\treturn false
end

-- Adding a child fires the parent chain's DescendantAdded, which is what the
-- shipped reader listens to. Firing it is the only way to test that it does.
local function add(parent, child)
\tchild.Parent = parent
\tparent._kids[#parent._kids + 1] = child
\tlocal n = parent
\twhile n ~= nil do
\t\tlocal s = rawget(n, 'DescendantAdded')
\t\tif s ~= nil then s:Fire(child) end
\t\tn = n.Parent
\tend
\treturn child
end

local function remove(parent, child)
\tfor i = 1, #parent._kids do
\t\tif parent._kids[i] == child then table.remove(parent._kids, i) break end
\tend
\tchild.Parent = nil
\tlocal n = parent
\twhile n ~= nil do
\t\tlocal s = rawget(n, 'DescendantRemoving')
\t\tif s ~= nil then s:Fire(child) end
\t\tn = n.Parent
\tend
\treturn child
end

-- ========================== MOCK RECORDER SURFACE =========================
local Config = { MaxGuiObjects = 3, MaxGuiLabels = 2 }

local Players = {}
local buoy = {}
local putCalls, evts = {}, {}
local lastPut = {}

local function put(key, value)
\tputCalls[#putCalls + 1] = { key = key, value = value }
\tlastPut[key] = value
end

local function emitEvt(kind, rest)
\tevts[#evts + 1] = tostring(kind) .. ' ' .. tostring(rest)
end

local function putsWithKey(k)
\tlocal t = {}
\tfor i = 1, #putCalls do
\t\tif putCalls[i].key == k then t[#t + 1] = putCalls[i] end
\tend
\treturn t
end

local function keysOffered()
\tlocal t = {}
\tfor i = 1, #putCalls do t[#t + 1] = putCalls[i].key end
\treturn t
end

local function evtOf(kind)
\tfor i = 1, #evts do
\t\tif string.sub(evts[i], 1, #kind + 1) == (kind .. ' ') then return evts[i] end
\tend
\treturn nil
end

local function reset()
\tputCalls, evts, lastPut = {}, {}, {}
end

-- `readoutDirty` is a real local in the recorder and a plain global here,
-- because the readout walk it belongs to is not extracted. What matters is that
-- a rebuild SETS it -- a player's label added mid-shift has to reach the sweep
-- that reads captions, or the screen is recorded for its flags and never for
-- its text.
readoutDirty = false

"""

TAIL = """
-- ========================== THE TREE ======================================
-- One player, one PlayerGui, and the recorder's own panel inside it -- because
-- that is where buildUi puts it, and a harness that left it out would be
-- handing the reader an easier tree than the one it ships against.
local player = new('Player', 'tester')
local pg = add(player, new('PlayerGui', 'PlayerGui'))
Players.LocalPlayer = player

-- The recorder's panel: a ScreenGui with a Frame and a TextLabel under it.
local own = add(pg, new('ScreenGui', 'TRGRecorder'))
local ownPanel = add(own, new('Frame', 'panel'))
local ownText = add(ownPanel, new('TextLabel', 'text'))
buoy.gui = own

-- The game's screens.
local hud = add(pg, new('ScreenGui', 'Hud'))
local hudFrame = add(hud, new('Frame', 'HudFrame'))
local hudLabel = add(hudFrame, new('TextLabel', 'TempLabel'))
local hudBtn = add(hudFrame, new('TextButton', 'PowerButton'))

local menu = add(pg, new('ScreenGui', 'Menu'))
local menuFrame = add(menu, new('Frame', 'MenuFrame'))
local menuLabel = add(menuFrame, new('TextLabel', 'TempLabel'))

-- Neither flag, and it claims to be a GuiObject.
local odd = add(pg, new('BizarreGui', 'OddOne'))
-- Not a GuiObject and not a LayerCollector: skipped before it is ever asked.
local layout = add(hudFrame, new('UIListLayout', 'Layout'))

-- The keys are NOT written down here. keyForLabel deepens a key until it is
-- free, starting at depth 2, so the third screen in the tree gets a different
-- key from the first, and spelling one out would make this file assert its own
-- guess about the naming rule instead of the rule. Every check below asks the
-- reader what it called the object.
local function keyOf(inst)
	for i = 1, #guiRecords do
		if guiRecords[i].inst == inst then return guiRecords[i].key end
	end
	return nil
end

local function seen(inst)
	local k = keyOf(inst)
	if k == nil then return nil end
	return lastPut[k]
end

-- The cap is raised for the behavioural checks so that every object under test
-- is inside it, and lowered only for the check that is about the cap.
Config.MaxGuiObjects = 99
reset()
buildGui()

-- ========================== G1 THE FLAGS ==================================
-- The screen answers Enabled and the frame answers Visible. Both are read, and
-- the arm a class-name test would have picked for the ScreenGui is the one that
-- raises -- so a reader that chose by class name cannot pass G1.
reset()
readGui()
check('G1 the HUD screen is a record', keyOf(hud) ~= nil, true)
check('G1 the frame under it is a record', keyOf(hudFrame) ~= nil, true)
check('G1 the layout is not a record', keyOf(layout), nil)
check('G1 the screen reads its Enabled', seen(hud), true)
check('G1 the frame reads its Visible', seen(hudFrame), true)

hud._enabled = false
reset()
readGui()
check('G1 a disabled screen reads false', seen(hud), false)
check('G1 the frame is unaffected by the screen', seen(hudFrame), true)

hud._enabled = true
hudFrame._visible = false
reset()
readGui()
check('G1 an invisible frame reads false', seen(hudFrame), false)
check('G1 the screen is unaffected by the frame', seen(hud), true)
hudFrame._visible = true

-- ========================== G2 THE PROBE ==================================
-- BizarreGui claims GuiObject and answers NEITHER flag. A class-name test picks
-- Visible for it, raises on the very first poll, and takes the whole poll with
-- it -- which is the whole run, since readGui sits inside the poll's pcall.
--
-- The rebuild is forced: the GUI event under test is emitted by buildGui, and a
-- poll that finds the tree clean never emits one -- so a test that read the tree
-- without dirtying it would be asserting over an empty event list and calling
-- the absence a pass.
reset()
buildGui()
readGui()
checkTrue('G2 a class that answers neither flag is not a record',
	keyOf(odd) == nil, 'it was registered anyway')
checkTrue('G2 and readGui did not raise over it',
	(select(1, pcall(readGui)) == true), 'readGui raised on the unreadable class')
local guiEvt = evtOf('GUI')
checkTrue('G2 the GUI event names the unreadable count', guiEvt ~= nil
	and string.find(guiEvt, 'unreadable=1', 1, true) ~= nil, tostring(guiEvt))

-- ========================== G3 THE RECORDER'S OWN PANEL ===================
check('G3 the panel is not a record', keyOf(ownPanel), nil)
check('G3 the panel text label is not a record', keyOf(ownText), nil)
check('G3 the panel screen is not a record', keyOf(own), nil)

-- Renaming it cannot put it back: the exclusion is by ancestry, not by name.
own.Name = 'SomethingElse'
reset()
buildGui()
readGui()
check('G3 renamed, the panel is still not a record', keyOf(ownPanel), nil)
check('G3 renamed, its label is still not a record', keyOf(ownText), nil)
own.Name = 'TRGRecorder'

-- ========================== G4 EXCLUSION IS NOT BY LUCK ===================
-- A Frame that is NOT under the panel, with a child whose name collides with the
-- panel's own child name. Both must be recorded, or the exclusion is a name test
-- wearing an ancestry costume.
local free = add(hudFrame, new('Frame', 'freePanel'))
local freeText = add(free, new('TextLabel', 'text'))
reset()
buildGui()
readGui()
checkTrue('G4 a frame outside the panel IS recorded',
	keyOf(free) ~= nil, 'it was excluded along with the panel')
checkTrue('G4 and its child is recorded even though the name collides',
	keyOf(freeText) ~= nil, 'the exclusion leaked past the panel')
remove(hudFrame, free)

-- ========================== G5 THE KEY IS UNIQUE ==========================
-- Two TempLabels, one per screen. A key built from the name alone collapses them
-- into one record holding its own dedup state, and one of the two then stops
-- reporting changes -- silently, which is exactly why keyForLabel deepens.
reset()
buildGui()
readGui()
local kh, km = keyOf(hudLabel), keyOf(menuLabel)
checkTrue('G5 two same-named labels get two keys',
	kh ~= nil and km ~= nil and kh ~= km,
	tostring(kh) .. ' vs ' .. tostring(km))
checkTrue('G5 and both were offered',
	seen(hudLabel) ~= nil and seen(menuLabel) ~= nil,
	'one of the two never reached put')

-- ========================== G6 THE CAP ====================================
Config.MaxGuiObjects = 3
reset()
buildGui()
readGui()
local guiEvt2 = evtOf('GUI')
checkTrue('G6 the cap is reported and the overflow is counted',
	guiEvt2 ~= nil and string.find(guiEvt2, 'over=0 ', 1, true) == nil,
	tostring(guiEvt2))
check('G6 the count reflects the cap', #guiRecords, 3)
checkTrue('G6 the overflow is a positive number',
	type(lastPut['g.over']) == 'number' and lastPut['g.over'] > 0,
	'over=' .. tostring(lastPut['g.over']))
Config.MaxGuiObjects = 99
reset()
buildGui()
readGui()

-- ========================== G7 MID-RUN ADDITIONS ==========================
-- A screen the game creates halfway through the shift has to be picked up, and
-- the pick-up has to reach the readout sweep as well as this reader.
reset()
readoutDirty = false
local late = add(pg, new('ScreenGui', 'LateScreen'))
checkTrue('G7 adding a screen sets the dirty flag', guiDirty == true,
	'DescendantAdded did not mark the tree dirty')
readGui()
checkTrue('G7 the late screen is a record after one poll',
	keyOf(late) ~= nil, 'it was never picked up')
checkTrue('G7 the rebuild also invalidates the readout sweep',
	readoutDirty == true,
	'a label added mid-shift would never be read for text')
checkTrue('G7 GMAP names the class of a screen',
	(string.find(evtOf('GMAP') or '', 'ScreenGui', 1, true) ~= nil), evtOf('GMAP'))

reset()
remove(pg, late)
checkTrue('G7 removing a screen sets the dirty flag', guiDirty == true,
	'DescendantRemoving did not mark the tree dirty')
reset()
readGui()
checkTrue('G7 the removed screen is gone from the records',
	keyOf(late) == nil, 'a destroyed screen is still being read')

-- ========================== G8 THE COUNTERS ===============================
reset()
readGui()
checkTrue('G8 every poll offers g.objects', #putsWithKey('g.objects') > 0, 'missing')
checkTrue('G8 every poll offers g.over', #putsWithKey('g.over') > 0, 'missing')
checkTrue('G8 every poll offers g.unreadable',
	#putsWithKey('g.unreadable') > 0, 'missing')
checkTrue('G8 every poll offers g.labels', #putsWithKey('g.labels') > 0, 'missing')

-- ========================== G9 THE READ IS CHEAP ==========================
-- The reader runs four times a second, and the whole argument for reading the
-- raw flag rather than the effective one is that the raw read is ONE property
-- access per object. So the accesses are COUNTED rather than the timing claimed.
--
-- Two different prices are pinned, and they are different on purpose: a REBUILD
-- pays a probe per candidate, which is what not guessing the class costs, and a
-- POLL pays exactly one access per record and nothing more -- no ancestor walk
-- and no second pcall.
FLAG_READS = 0
reset()
readGui()
check('G9 one poll reads exactly one flag per record', FLAG_READS, #guiRecords)

FLAG_READS = 0
buildGui()
local perObject = FLAG_READS / #guiRecords
checkTrue('G9 a rebuild pays one probe per object',
	perObject >= 1 and perObject < 2,
	'probes per object = ' .. tostring(perObject))
reset()
readGui()

-- ========================== G10 THE FLAG IS NOT THE VIEW ==================
-- Documented, deliberate, and pinned here so it cannot be quietly "fixed" into a
-- per-poll ancestor walk. A Visible=true label under a Visible=false Frame reads
-- true: the raw flag is what is read. What closes the gap for free is the
-- ScreenGui's own Enabled, which IS read, and G1 pins that.
hudFrame._visible = false
reset()
readGui()
check('G10 a Visible child under a hidden frame still reads true',
	seen(hudLabel), true)
check('G10 the frame it is hiding under reads false', seen(hudFrame), false)
check('G10 and the screen above both is unaffected', seen(hud), true)
hudFrame._visible = true

local report = table.concat(results, string.char(10))
if string.find(report, 'FAIL', 1, true) ~= nil and io ~= nil and io.stderr ~= nil then
	io.stderr:write(report .. string.char(10))
	os.exit(1)
end
return report
"""


def slice_between(src: str, start_marker: str, end_marker: str, what: str) -> str:
    start = src.find(start_marker)
    if start < 0:
        sys.exit("could not find the start of %s" % what)
    end = src.find(end_marker, start)
    if end < 0:
        sys.exit("could not find the end of %s" % what)
    return src[start:end]


def extract_key_for_label(src: str) -> str:
    m = re.search(r"^local function keyForLabel\(label, seen\)\n.*?^end$", src, re.S | re.M)
    if not m:
        sys.exit("could not find keyForLabel -- did it get rewritten?")
    return m.group(0)


def main(argv) -> int:
    # The two paths are overridable so that selftest_gui.py can point the very
    # same extraction at a deliberately broken copy of the recorder.  A mutation
    # test against a different builder would be testing the builder.
    src_path = Path(argv[1]) if len(argv) > 1 else RECORDER
    out_path = Path(argv[2]) if len(argv) > 2 else OUT
    src = src_path.read_text(encoding="utf-8")

    state_block = slice_between(
        src,
        "-- ==================== PLAYER GUI: STATE",
        "-- ==================== READOUT DISCOVERY",
        "the player-GUI state block")
    fn_block = slice_between(
        src,
        "-- ========================== PLAYER GUI ====",
        "-- ========================== FLOW ==",
        "the player-GUI function block")

    for name, block in (("state", state_block), ("functions", fn_block)):
        for open_c, close_c in (("(", ")"), ("{", "}")):
            if block.count(open_c) != block.count(close_c):
                sys.exit("the %s block is unbalanced on %r: %d vs %d"
                         % (name, open_c, block.count(open_c), block.count(close_c)))

    for needle in ("local function ensureGuiRoot", "local function buildGui",
                   "local function readGui", "local function flagReaderFor"):
        if needle not in fn_block:
            sys.exit("the function block is missing %r" % needle)
    for needle in ("local guiRecords, guiDirty", "local isOwnGui"):
        if needle not in state_block:
            sys.exit("the state block is missing %r" % needle)

    key_fn = extract_key_for_label(src)

    body = HEAD + state_block + "\n" + key_fn + "\n\n" + fn_block + "\n" + TAIL
    out_path.write_text(body, encoding="utf-8", newline="\n")
    raw = out_path.read_bytes()
    print("wrote %s" % out_path)
    print("  lines %d  bytes %d" % (raw.decode("utf-8").count("\n"), len(raw)))
    print("  extracted state lines %d  function lines %d"
          % (state_block.count("\n") + 1, fn_block.count("\n") + 1))
    print("  backslash bytes %d  (must be 0: the editor decodes escapes once)"
          % raw.count(0x5C))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
