"""Prove the shift-clock crossings, which are the one pair of lines that lied.

`announceClock` turns the 12-hour quota clock into a named event, because the
operator's own rule for "the core is up" is `B1`: the clock is past 12:00PM. It
was written for a run INJECTED ON A COLD CORE, where the first crossing of noon
and the start of the shift are the same moment. It was then used on a run
injected MID-SHIFT, and the difference is not cosmetic:

    EVT3490 CLOCK the clock is back at 12:00 PM
    EVT3495 CLOCK the clock passed 12:00PM: the shift has started

Two lines, 60 s apart, in the middle of a shift, in
`Data/flow/original_260926-230049`. `m.temp` held 12865 -> 12979 F across both,
so nothing ended and nothing started. The cause is arithmetic and was always
there: `q.up` is `q.clock > 0` over a dial that puts noon at 0, so 12:00 PM is
the one minute that reads false. A dial already past noon at inject has to come
all the way round before it reads past noon again, which makes the second line a
WRAP -- and it is indistinguishable from the real crossing, because it IS the
real crossing.

What is at 12:00PM is the place speaking about itself, not an inference:
`INGAME_MANUAL` 114 and 148 say `12PM marks the beginning of the Equinox Event`,
against a shift of 6:00 AM to 6:00 PM (`DECISIONS` 28). Noon is mid-shift.

So the region is extracted from the SHIPPED recorder -- `announceClock` and the
three latches it closes over, contiguous, hence a region and not a function --
and driven against a mock clock. The assertions are in BOTH directions, because
this fix has two ways to be wrong:

  * K1 is the defect. A mid-shift inject must not announce a shift start.
  * K2 is the opposite failure, and it is the one a careless fix produces: a run
    injected before the shift starts MUST still announce the crossing. Swallowing
    everything would make K1 pass and throw away the thing the event is for.
  * K4 pins that the reading is not discarded along with the claim: the wrap
    message carries the raw `q.timeText`, so the moment stays locatable.

    python _tools/build_clock_test.py
    /d/Lua/5.1/lua.exe -e "print(assert(loadfile('_tools/_clock_states.luau'))())"
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
RECORDER = ROOT / "TRG_original_recorder.luau"
OUT = ROOT / "_clock_states.luau"

START = "local clockSeen, clockUp, clockStartedUp = false, false, false"

# The two messages the harness asserts BY NAME. If either is rewritten the
# builder stops, so a green run cannot mean "the expectations drifted".
WRAP_FRAGMENT = "-- the dial, not a shift boundary: the core was already up at inject"
COLD_MESSAGE = "the clock passed 12:00PM: the shift has started"

HEAD = """--!nocheck
-- GENERATED by _tools/build_clock_test.py -- edit that file, not this one.
--
-- `announceClock` and the latches it closes over are EXTRACTED from
-- _tools/TRG_original_recorder.luau. Everything else is mock; no Roblox API and
-- no DataModel instance is touched.

local results = {}
local function say(s) results[#results + 1] = tostring(s) end

local function check(name, got, want)
\tlocal ok = (got == want)
\tsay((ok and 'PASS ' or 'FAIL ') .. name)
\tif not ok then
\t\tsay('     got  [' .. tostring(got) .. ']')
\t\tsay('     want [' .. tostring(want) .. ']')
\tend
end

local function checkTrue(name, cond, why)
\tsay((cond and 'PASS ' or 'FAIL ') .. name)
\tif not cond then say('     ' .. why) end
end

-- emitEvt and the console line, captured instead of written. `print` is shadowed
-- so the region's own console line is captured too: it is the line the operator
-- reads, and losing it is a real way to break this without failing K1.
local emitted = {}
local said = {}
local function emitEvt(kind, message)
\temitted[#emitted + 1] = kind .. '|' .. message
end
local print = function(s) said[#said + 1] = tostring(s) end

-- `last` is the recorder's carried-forward reading table: a key holds the last
-- value SEEN, not the value of this poll. The mock sets it directly, which is
-- exactly what put() does. Rebound by reset(), not mutated in place, so a test
-- cannot inherit a key from the one before it.
local last = {}

"""

TAIL = """
-- ---------------------------------------------------------------- helpers --
-- Every test states only the reading it is about. A test that has to set up six
-- fields to say one thing is a test whose failure is ambiguous.
local function reset(up, text)
\temitted, said, last = {}, {}, {}
\tif up ~= nil then last['q.up'] = up end
\tif text ~= nil then last['q.timeText'] = text end
\tclockSeen, clockUp, clockStartedUp = false, false, false
end

-- ------------------------------------------- K1 the mid-shift inject ------
-- The shipped recorder emitted `the clock is back at 12:00 PM` and then `the
-- clock passed 12:00PM: the shift has started` here, 60 s apart, on a file whose
-- temperature never moved. This is the assertion that guards it.
reset(true, '11:50 PM')
announceClock()
check('K1 the inject read is a state, not an arrival', emitted[1],
\t'CLOCK|the clock already reads past 12:00PM at inject; the core is up')

last['q.up'], last['q.timeText'] = false, '12:00 PM'
announceClock()
last['q.up'], last['q.timeText'] = true, '12:01 PM'
announceClock()

check('K1 three events in total', #emitted, 3)
checkTrue('K1 no shift start is announced after a mid-shift inject',
\tstring.find(table.concat(emitted, ' '), 'shift has started') == nil,
\t'an in-game day wrap was announced as the start of a shift')
checkTrue('K1 both wrap events name themselves a dial move',
\tstring.find(emitted[2], 'the dial') ~= nil and
\tstring.find(emitted[3], 'the dial') ~= nil,
\t'the wrap cannot be told from a shift boundary by a reader of the file')

-- ------------------------------------------ K4 the reading is still there --
-- Not swallowed: the wrap message carries the raw text, so the crossing can
-- still be located in the file by hand. Refusing to interpret a reading is not
-- the same as dropping it, and a fix that dropped it would pass K1.
checkTrue('K4 the moment stays locatable in the file',
\tstring.find(emitted[3], '12:01 PM') ~= nil,
\t'the wrap message does not carry q.timeText, so the moment was destroyed')

-- ------------------------------------ K2 the cold opening is preserved ----
-- The opposite failure, and the one a careless fix produces. A run injected
-- before the shift starts reads q.up false, so the first false-to-true IS the
-- shift. Swallowing it would make K1 pass and delete the event's whole purpose.
reset(false, '6:00 AM')
announceClock()
check('K2 the inject read is the not-up-yet state', emitted[1],
\t'CLOCK|the clock reads 6:00 AM at inject; the core is not up yet')
last['q.up'], last['q.timeText'] = true, '12:01 PM'
announceClock()
check('K2 the cold opening still announces the shift', emitted[2],
\t'CLOCK|the clock passed 12:00PM: the shift has started')
checkTrue('K2 and still says it on the console', #said == 1,
\t'the console line the operator reads went missing')

-- ------------------------------------------------- K3 no reading, no claim --
-- An unparsed clock is not a clock reading noon. The recorder must announce a
-- state it has, and nothing else.
reset(nil, nil)
announceClock()
check('K3 a clock that has not parsed says nothing', #emitted, 0)

-- ------------------------------------------------- K5 steady state is quiet --
-- A chatty event is worse than no event: it buries the crossing in its own
-- repetition. Same reading, four calls, one line.
reset(true, '11:50 PM')
announceClock()
announceClock()
announceClock()
announceClock()
check('K5 a steady clock emits once', #emitted, 1)

-- ---------------------------------------------------------------- report --
-- Every line goes out on success too, not only on failure. A suite that prints
-- nothing when it passes cannot be counted: the mutation proofs beside this file
-- read the PASS lines to establish a baseline, and `0 assertions PASS` is
-- indistinguishable from a harness that ran no assertions at all.
local lines, pass, fail = {}, 0, 0
for _, r in ipairs(results) do
\tlines[#lines + 1] = r
\tif string.sub(r, 1, 4) == 'PASS' then pass = pass + 1 else fail = fail + 1 end
end
local summary = ('clock: %d PASS, %d FAIL'):format(pass, fail)
if fail > 0 then
\tio.stderr:write(table.concat(lines, string.char(10)) .. string.char(10))
\tio.stderr:write(summary .. string.char(10))
\tio.stderr:flush()
\tos.exit(1)
end
io.write(table.concat(lines, string.char(10)) .. string.char(10))
return summary
"""


def extract_clock_region(path: Path) -> str:
    """The clock latches and announceClock, contiguous and shipped.

    A region and not a function because announceClock closes over three
    upvalues, one of which (`clockStartedUp`) is the fix. Declaring them here
    instead would be this file's copy of the state the recorder keeps, and a
    harness that agrees with a copy proves nothing -- it would go green on the
    shipped recorder with the door deleted.
    """
    src = path.read_text(encoding="utf-8")
    start = src.find(START)
    if start < 0:
        sys.exit("could not find the clock latches -- did announceClock get rewritten?")
    m = re.search(r"^local function announceClock\(\)\n.*?^end$", src[start:], re.S | re.M)
    if not m:
        sys.exit("could not find announceClock after the latches")
    block = src[start:start + m.end()]
    for open_c, close_c in (("(", ")"), ("{", "}")):
        if block.count(open_c) != block.count(close_c):
            sys.exit("the clock region is unbalanced on %r: %d vs %d"
                     % (open_c, block.count(open_c), block.count(close_c)))
    if not block.rstrip().endswith("end"):
        sys.exit("the clock region does not end in `end`")
    for needle in (START, "local function announceClock", "clockStartedUp",
                   WRAP_FRAGMENT, COLD_MESSAGE):
        if needle not in block:
            sys.exit("the clock region is missing %r -- the harness would be "
                     "asserting a message the recorder no longer writes" % needle)
    return block


def main() -> int:
    block = extract_clock_region(RECORDER)
    OUT.write_text(HEAD + block + "\n" + TAIL, encoding="utf-8", newline="\n")
    raw = OUT.read_bytes()
    print("wrote %s" % OUT)
    print("  lines %d  bytes %d  extracted lines %d"
          % (raw.decode("utf-8").count("\n"), len(raw), block.count("\n") + 1))
    print("  backslash bytes %d  (must be 0: the editor decodes escapes once)"
          % raw.count(0x5C))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
