"""Prove the end-of-shift rule, which is the one rule whose ABSENCE cost a run.

The 18:35 capture is 1,461,518 bytes of correct data with no `## RECEIPT` on the
end of it, and the reason is not subtle: `s.GameActive` went false on the very
last sample the script ever took, no branch looked at it, and the client was
killed during the `task.wait` that followed. Every byte was recorded and the file
still cannot be replayed as a shift, because a shift whose ending is unknown is
a shift nobody can cite.

So `endReason` is extracted from the SHIPPED recorder -- along with the counter
declarations it closes over, which is why this harness extracts a REGION and not
just a function -- and driven against a mock plant. It is not tested anywhere
else, and it is the piece most likely to be got wrong in the direction that
matters, because BOTH directions of failure are silent:

  * Seal too LATE, and the client dies first: no receipt, which is the 18:35
    file exactly. Nothing in the recording says so.
  * Seal too EARLY, and the file is truncated with a valid-looking receipt on
    it -- which is WORSE, because it looks finished. The A1 answer creates this
    risk where it did not exist before: a NEW SHIFT OPENS WITH THE CORE COLD,
    a cold core sits below the cold-trip line by definition, and a level test
    would therefore seal two seconds after inject with nothing recorded. E2 is
    the assertion for that, and it is the reason `everRan` exists at all.

The counters and the `everRan` latch are read from the shipped source rather
than re-declared here. Duplicating them would make the harness agree with a
version of the state that the recorder does not have, which is the failure mode
that makes a green test worthless.

    python _tools/build_end_test.py
    /d/Lua/5.1/lua.exe -e "print(assert(loadfile('_tools/_end_states.luau'))())"
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
RECORDER = ROOT / "TRG_original_recorder.luau"
OUT = ROOT / "_end_states.luau"

HEAD = """--!nocheck
-- GENERATED by _tools/build_end_test.py -- edit that file, not this one.
--
-- `endReason` and the state it closes over are EXTRACTED from
-- _tools/TRG_original_recorder.luau. Everything else is mock; no Roblox API and
-- no DataModel instance is touched.

local results = {}
local function say(s) results[#results + 1] = tostring(s) end

local function check(name, got, want)
\tlocal ok = (got == want)
\tsay((ok and 'PASS ' or 'FAIL ') .. name)
\tif not ok then
\t\tsay('     got  [' .. tostring(got) .. ']')
\t\tsay('     want [' .. tostring(want) .. ']')
\tend
end

local function checkTrue(name, cond, why)
\tsay((cond and 'PASS ' or 'FAIL ') .. name)
\tif not cond then say('     ' .. why) end
end

-- The recorder's own numbers, or the dwells under test would be this file's
-- opinion of them rather than the shipped ones.
local Config = {
\tSampleInterval = 0.25,
\tCoreThresholds = {5600, 17500, 29500, 39000},
\tLowTripF = 2000,
\tMeltdownF = 39000,
\tSealColdSamples = 8,
\tSealHotSamples = 8,
\tSealDownSamples = 40,
\tSealDeadSamples = 40,
}

-- `last` is the recorder's carried-forward reading table: a key holds the last
-- value SEEN, not the value of this poll. The mock sets it directly, which is
-- exactly what put() does.
local last = {}
local sawDown = false

"""

TAIL = """
-- ---------------------------------------------------------------- helpers --
-- Every test starts from a plant that is running and healthy, then states only
-- the one thing it is about. A test that has to set up six fields to say one
-- thing is a test whose failure is ambiguous.
local function reset()
\tlast = {}
\tlast['s.GameActive'] = true
\tlast['s.GameFail'] = false
\tlast['s.MainframeMeltdown'] = false
\tlast['m.temp'] = 9000
\tsawDown = false
\teverRan = false
\tcoldPolls, hotPolls, downPolls, deadPolls = 0, 0, 0, 0
\tflagWas = {}
end

-- Polls the rule n times and returns the reason it fired on, or nil if it never
-- did. Returned rather than asserted inside, so the COUNT that matters can be
-- asserted by the caller: "it eventually fires" and "it fires on the eighth
-- poll" are different claims and only the second one pins a dwell.
local function run(n)
\tfor i = 1, n do
\t\tlocal r = endReason()
\t\tif r ~= nil then return r, i end
\tend
\treturn nil, n
end

-- ------------------------------------------------- E1 the 18:35 defect -----
-- GameActive true -> false. The whole point is the TIMING: the client is killed
-- during the wait that follows the poll that reported it, so this must fire on
-- the FIRST call after the edge and not after a dwell. A version of this rule
-- with a grace period would pass a test that only asked whether it fired at all.
reset()
check('E1 no seal while the shift is running', endReason(), nil)
last['s.GameActive'] = false
check('E1 true to false seals on the FIRST poll', run(1),
\t'shift over (GameActive true to false)')

-- ------------------------------------------------- E2 the cold opening -----
-- THE ASSERTION THAT PROTECTS THE WHOLE NEW FLOW. A shift opens with the core
-- cold: 900 F, below the 2000 F trip line, and below the 5600 F run line too --
-- so the recorder's own boundary has latched `sawDown` as well. Both level tests
-- are true simultaneously, in the state every run now STARTS in, and this must
-- stay silent indefinitely.
reset()
last['m.temp'] = 900
sawDown = true
checkTrue('E2 a cold opening never seals itself', run(200) == nil,
\t'a cold shift start sealed the file, so every run would die two seconds in')

-- And it is specifically `everRan` doing the work, not the absence of a signal:
-- the same cold readings AFTER the core has run must trip. If this passed only
-- because sawDown was false, E2 would be proving nothing.
reset()
last['m.temp'] = 9000
endReason()
last['m.temp'] = 900
local _, at = run(Config.SealColdSamples + 5)
check('E2 the same reading trips once the core has run', at, Config.SealColdSamples)

-- ------------------------------------------------- E3 no readout -----------
-- A dead sensor is not a dead reactor, and it is not the end of a shift either.
-- Sealing on a missing temperature would end a recording on a mis-read, and the
-- temperature is the one key this rule cannot do without.
reset()
last['m.temp'] = nil
checkTrue('E3 a missing readout never seals', run(500) == nil,
\t'a missing temperature sealed the file')

-- ------------------------------------------------- E4 the cold trip --------
-- The dwell, pinned at both ends: one poll short is not enough, and the poll the
-- configuration names is. The core is at 1500, under LowTripF and over nothing
-- else, so no other arm can fire and the count is unambiguous.
reset()
last['m.temp'] = 9000
endReason()
last['m.temp'] = 1500
check('E4 one poll short of the cold dwell', run(Config.SealColdSamples - 1), nil)
check('E4 the cold dwell fires on its own poll', run(1),
\t'cold trip (under 2000 F for ' .. tostring(Config.SealColdSamples) .. ' polls)')

-- A single dip must NOT accumulate: the counter is consecutive, or a core that
-- grazes the line eight times over an hour would seal on the eighth touch.
-- The fire is COUNTED rather than polled for at the end, because an accumulating
-- counter fires inside this loop -- and a version of this test that only looked
-- at the plant after the loop would find a healthy core, return nil, and pass
-- while the file had already been sealed mid-loop.
reset()
last['m.temp'] = 9000
endReason()
local grazed = false
for i = 1, 20 do
\tlast['m.temp'] = 1500
\tif endReason() ~= nil then grazed = true end
\tlast['m.temp'] = 9000
\tif endReason() ~= nil then grazed = true end
end
checkTrue('E4 the cold dwell counts consecutive polls', not grazed,
\t'the cold counter accumulated across a recovered dip instead of resetting')

-- ------------------------------------------------- E5 the other flags ------
-- The priming `endReason()` is not ceremonial: flagEdge needs to have SEEN the
-- rest value before it can call a change a transition, so a plant that is
-- flipped before the first poll produces no edge by construction. Every scenario
-- here primes for the same reason -- and E5's negative case below depends on the
-- priming being ABSENT, which is what makes it a different test.
reset()
endReason()
last['s.GameFail'] = true
check('E5 GameFail false to true seals', run(1), 'shift failed (GameFail false to true)')
reset()
endReason()
last['s.MainframeMeltdown'] = true
-- NAMED AS THE MACHINE ROOM, AND THE TEMPERATURE IS DELIBERATELY NORMAL HERE.
-- The operator separated the two meltdowns (`D9`: 是机房熔毁又不是核心熔毁) after this
-- file had been labelling the flag `meltdown (over 39000 F)`. The 18:35 capture is
-- why the distinction is not pedantry: the flag went true at t=719.86 with the
-- monitor reading about 13000 F, so the old label reported a 39000-degree core
-- meltdown that had never happened. `m.temp` is set to a healthy value below for
-- the same reason -- with an absurd temperature in place, the core meltdown arm
-- could fire first and this assertion would pass for the wrong cause.
last['m.temp'] = 13000
check('E5 the machine room meltdown seals, named as the machine room',
	run(1), 'machine room meltdown (MainframeMeltdown false to true)')

-- ------------------------------------------------- E5b the core meltdown ---
-- The other half of the split, and the arm that had no reader at all until the
-- flag was taken away from it: `Config.MeltdownF` sat in the config with nothing
-- looking at it, because the machine-room flag had been standing in for the core
-- rule the operator gave (`A2`: over 39000 F and nothing else). Both directions
-- of the temperature scale now have an arm, and this is the hot one.
--
-- Counted rather than polled for, for the same reason as E4: the arm accumulates
-- a dwell, so a version of this test that only looked at the end state would pass
-- on a plant that had already sealed mid-loop.
reset()
last['m.temp'] = 9000
endReason()
last['m.temp'] = 40000
checkTrue('E5b the hot arm waits for its dwell', run(1) == nil,
	'the core meltdown arm fired on a single poll, before its dwell had run')

-- One poll short, then the poll that reaches the dwell. `run(n)` performs n
-- polls and returns the first non-nil reason, so the first call is the count-down
-- and the second is the firing poll -- and the pair pins that the arm counts
-- rather than firing on the last of them by luck.
reset()
last['m.temp'] = 9000
endReason()
-- The temperature has to be raised AFTER the priming poll, or the arm counts
-- nothing and the "one poll short" assertion below passes for the wrong reason:
-- it did exactly that on the first write of this test, reporting a silent arm
-- that was only ever reading a healthy core.
last['m.temp'] = 40000
local hotShort = run(7)
local hotFired = run(1)
checkTrue('E5b the hot arm is silent one poll short',
	hotShort == nil, 'the core meltdown arm fired with a poll still to count')
check('E5b the core meltdown seals over its line', hotFired,
	'core meltdown (over 39000 F for 8 polls)')

-- A flag that is ALREADY in its end state when the recorder arrives produces no
-- edge, and that is deliberate: the alternative is sealing at inject on a plant
-- nobody has looked at yet. It is caught by the deadPolls arm instead. No
-- priming here on purpose -- priming is exactly what would create the edge.
reset()
last['s.GameFail'] = true
checkTrue('E5 a level is not an edge', run(1) == nil,
\t'a flag that was already set was read as a transition')

-- ------------------------------------------------- E6 already-dead session --
-- The only arm that does not need an edge, for a session that was over before
-- the script arrived. The temperature is above LowTripF (3000) so the cold arm
-- cannot fire, and sawDown is false so the down arm cannot either -- which
-- leaves exactly one thing that can produce a reason here.
--
-- `flagWas` is cleared between setting the flag and polling, because that IS the
-- scenario: the flag was already false when the recorder started watching, so
-- there is no true->false transition to observe and the E1 arm cannot answer.
-- Without the clear this test would measure the edge instead, fire on its first
-- poll, and pass while testing nothing about the dead arm.
reset()
last['m.temp'] = 9000
endReason()
last['s.GameActive'] = false
flagWas = {}
local _, at2 = run(Config.SealDeadSamples + 5)
check('E6 a session that ended before inject still seals', at2, Config.SealDeadSamples)

-- And it is gated on the core having run, so it cannot fire on the cold opening
-- either. Without the gate, E2's plant plus a GameActive that reads false at
-- inject would seal ten seconds in.
reset()
last['m.temp'] = 900
last['s.GameActive'] = false
checkTrue('E6 the dead arm is gated too', run(500) == nil,
\t'an unstarted cold core sealed on GameActive alone')

-- ------------------------------------------------- E7 a missing key ---------
-- Absent, not false. A capture with no s.GameActive in it at all -- a different
-- place, a renamed folder, a Stats tree that has not spawned yet -- must not
-- read as "the shift is over", or the recorder seals itself on arrival.
reset()
last['s.GameActive'] = nil
checkTrue('E7 an absent flag is not a dead shift', run(500) == nil,
\t'a nil read as false and sealed the file')

-- ------------------------------------------------- E8 precedence ------------
-- The reason is what a reader sees first, so when several arms are satisfiable
-- at once it must name the most definitive: the shift ended, not a cold trip
-- that happens to be true on the same poll. The 18:35 tail is exactly this
-- shape -- GameActive false arrived in the same poll as a temperature of 902.
reset()
last['m.temp'] = 9000
endReason()
last['m.temp'] = 900
sawDown = true
last['s.GameActive'] = false
check('E8 the shift ending outranks the cold trip', run(1),
\t'shift over (GameActive true to false)')

-- ------------------------------------------------------ report + exit ------
local report = table.concat(results, string.char(10))

if string.find(report, 'FAIL', 1, true) ~= nil and io ~= nil and io.stderr ~= nil then
\tio.stderr:write(report .. string.char(10))
\tos.exit(1)
end
return report
"""


def extract_end_region(path: Path) -> str:
    """The counter declarations, flagEdge and endReason, contiguous and shipped.

    A region and not a function because endReason closes over five upvalues.
    Declaring those here instead would be this file's copy of the state the
    recorder keeps, and a harness that agrees with a copy proves nothing.
    """
    src = path.read_text(encoding="utf-8")
    start = src.find("local everRan = false")
    if start < 0:
        sys.exit("could not find the everRan latch -- did endReason get rewritten?")
    m = re.search(r"^local function endReason\(\)\n.*?^end$", src[start:], re.S | re.M)
    if not m:
        sys.exit("could not find endReason after the latch")
    block = src[start:start + m.end()]
    for open_c, close_c in (("(", ")"), ("{", "}")):
        if block.count(open_c) != block.count(close_c):
            sys.exit("the end region is unbalanced on %r: %d vs %d"
                     % (open_c, block.count(open_c), block.count(close_c)))
    if not block.rstrip().endswith("end"):
        sys.exit("the end region does not end in `end`")
    for needle in ("local function flagEdge", "local function endReason"):
        if needle not in block:
            sys.exit("the end region is missing %r" % needle)
    return block


def main() -> int:
    block = extract_end_region(RECORDER)
    OUT.write_text(HEAD + block + "\n" + TAIL, encoding="utf-8", newline="\n")
    raw = OUT.read_bytes()
    print("wrote %s" % OUT)
    print("  lines %d  bytes %d  extracted lines %d"
          % (raw.decode("utf-8").count("\n"), len(raw), block.count("\n") + 1))
    print("  backslash bytes %d  (must be 0: the editor decodes escapes once)"
          % raw.count(0x5C))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
