"""Prove the flow boundary: what counts as a DOWN, and what is allowed to end a run.

THIS HARNESS EXISTS BECAUSE OF THE 12:32 RUN. The operator watched the monitor fall
to 5586 F, brought the core back, and the script sealed anyway -- on a live shift,
with `s.GameActive` true the whole way through, every click in the window a
`Coolant*-OFF`. The recorder had called that stall a shutdown and then a restart.
Two rules were involved and neither had a harness:

  * the flow boundary inside `pollOnce` had NO test at all -- it is the one state
    machine in the file that was never extracted, and it is the one that decides
    whether the file lives or dies;
  * the DOWN backstop in `endReason` DID have a harness, but nothing in it ever
    made the arm fire, so the arm's only real behaviour was unobserved.

`endReason`'s half is covered in build_end_test.py (E9). This file covers the flow
boundary, which is where the DOWN and UP edges are actually produced.

WHERE THE SUBJECT COMES FROM. Three REGIONS of the shipped recorder, extracted by
text and stitched in their original order -- north of `flowStep` they are the
recorder's own declarations, not this file's copy of them:

  1. `local sawDown`..`local flowArmed`  -- the flow's own latches
  2. `local running, lowRun, lowDown, settle = ...`  -- the countdowns, declared
     in the FLOW section header rather than beside the latches
  3. the tail of `pollOnce`, from `if not flowArmed then` to the function's
     closing `end` -- verbatim, and wrapped here in a function that takes exactly
     what `pollOnce` had in scope for it: `isRunning`.

Region 2 is why this is not one contiguous slice: the recorder keeps its flow
latches next to the click hooker and its countdowns two thousand lines later, in
the section that is about them. Test-only copies of those six variables would make
the harness agree with a version of the state the recorder does not have -- so they
are extracted, including their initial values, which a copy would get wrong first.

    python _tools/build_flow_test.py
    /d/Lua/5.1/lua.exe -e "print(assert(loadfile('_tools/_flow_states.luau'))())"
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
RECORDER = ROOT / "TRG_original_recorder.luau"
OUT = ROOT / "_flow_states.luau"

HEAD = """--!nocheck
-- GENERATED by _tools/build_flow_test.py -- edit that file, not this one.
--
-- The flow latches, the countdowns and the boundary itself are EXTRACTED from
-- _tools/TRG_original_recorder.luau. Everything else is mock: no Roblox API and no
-- DataModel instance is touched.

local results = {}
local function say(s) results[#results + 1] = tostring(s) end

local function check(name, got, want)
\tlocal ok = (got == want)
\tsay((ok and 'PASS ' or 'FAIL ') .. name)
\tif not ok then
\t\tsay('     got  [' .. tostring(got) .. ']')
\t\tsay('     want [' .. tostring(want) .. ']')
\tend
end

local function checkTrue(name, cond, why)
\tsay((cond and 'PASS ' or 'FAIL ') .. name)
\tif not cond then say('     ' .. why) end
end

-- The dwells under test are read out of the recorder's own Config table by the
-- builder, so this is not a second opinion about them -- a copy here would let the
-- shipped numbers change and this file keep passing.
local Config = {
"""

PHASE_STUB = """
-- `emitPhase` is the recorder's own announcer, stubbed to record -- and declared
-- BEFORE the boundary, because `flowStep` closes over it, and a `local` declared
-- after the function is a different variable entirely. This file found that the
-- hard way on its first run: the stub sat in the tail and the boundary called a nil
-- global.
--
-- The phase SEQUENCE is the observable that matters here. The 12:32 complaint was
-- not that the recorder decided wrongly in private -- it is that the log said
-- "shutdown" and then "restart" for what was a stall. A recovery has to be
-- ANNOUNCED as a recovery, so an emitted-nothing RECOVER is a failure this file
-- must be able to see.
local phaseLog = {}
local function emitPhase(name, note) phaseLog[#phaseLog + 1] = name end
local function phases() return table.concat(phaseLog, ' ') end
"""

TAIL = """
-- ---------------------------------------------------------------- helpers --
local function reset()
\tsawDown, startedSinceDown, flowArmed = false, false, false
\trunning, lowRun, lowDown, settle = false, 0, 0, 0
\tphaseLog = {}
end

-- Polls the boundary n times with one reading and returns how many of those polls
-- answered `true`. Counted rather than returned-as-a-boolean because the count is
-- the claim that matters in the direction this file exists for: "seals eventually"
-- and "never seals in two hundred polls" are the same single `false` to a caller
-- that stops at the first answer.
local function poll(isRunning, n)
\tlocal fired = 0
\tfor i = 1, n do
\t\tif flowStep(isRunning) then fired = fired + 1 end
\tend
\treturn fired
end

-- ------------------------------------------------- F1 arming the boundary ----
-- A cold core must not arm. The flow's own boundary reads the same threshold the
-- end rule does, so a shift that opens cold -- which is now how EVERY run starts
-- -- sits below the line and counts DOWN before it has ever counted up; `flowArmed`
-- is what stops that from being read as a shutdown before the core has been lit.
reset()
poll(true, Config.DebounceSamples - 1)
check('F1 the flow is not armed one poll short', flowArmed, false)
poll(true, 1)
check('F1 arming takes the debounce it names', flowArmed, true)
check('F1 arming is announced exactly once', phases(), 'RUN')

reset()
poll(false, 50)
check('F1 a cold core never arms the flow', flowArmed, false)
checkTrue('F1 a cold core is not announced', phases() == '',
\t'an unlit core was announced as running')

-- Consecutive, not cumulative: a reading that flickers across the line must not
-- accumulate its way to an arming.
reset()
for i = 1, 20 do
\tpoll(true, 1)
\tpoll(false, 1)
end
check('F1 the arming count is consecutive', flowArmed, false)

-- ------------------------------------------------- F2 the DOWN edge ----------
reset()
poll(true, Config.DebounceSamples)
poll(false, Config.DebounceSamples - 1)
check('F2 no DOWN one poll short', sawDown, false)
poll(false, 1)
check('F2 the DOWN edge takes its debounce', sawDown, true)
check('F2 the DOWN is announced', phases(), 'RUN DOWN')

reset()
poll(true, Config.DebounceSamples)
for i = 1, 20 do
\tpoll(false, 1)
\tpoll(true, 1)
end
check('F2 the DOWN count is consecutive too', sawDown, false)

-- ------------------------------------------------- F3 the 12:32 regression --
-- THE WHOLE POINT OF THIS FILE. Run, stall, come back -- and nothing was lit. The
-- old boundary took the UP path on the temperature alone, started the settle
-- countdown, and the file sealed itself 24 polls later; the DOWN backstop was
-- counting underneath it the whole time and would have sealed it anyway.
--
-- 200 polls is well past both dwells. The claim is not "it takes longer", it is
-- that a stall which recovers cannot end a run at ANY poll count.
reset()
poll(true, Config.DebounceSamples)
poll(false, Config.DebounceSamples)
check('F3 the stall is a DOWN while it lasts', sawDown, true)
local fired = poll(true, 200)
check('F3 a stall that recovers never reports the flow complete', fired, 0)
check('F3 the recovery clears the down state', sawDown, false)
check('F3 the recovery is announced', phases(), 'RUN DOWN RECOVER')
check('F3 the stall was not a relight', startedSinceDown, false)

-- ------------------------------------------------- F4 the relight ------------
-- The complementary direction, and the one that MUST still end a run: the operator
-- lit the core again. `startedSinceDown` is set here the way the click hooker sets
-- it, from the same label the log prints.
reset()
poll(true, Config.DebounceSamples)
poll(false, Config.DebounceSamples)
startedSinceDown = true
poll(true, Config.DebounceSamples)
check('F4 the relight is an UP', phases(), 'RUN DOWN UP')

-- F4 b THE RECOVERY DEBOUNCE. Arming the flow leaves `lowRun` AT the debounce --
-- it is the same counter -- so if the DOWN edge does not zero it, the first hot
-- poll after a stall satisfies `lowRun >= Config.DebounceSamples` and the UP fires
-- on one poll. The debounce then holds while a shift warms up and stops holding
-- for every recovery after it, which is worse than not having it: the receipt says
-- a dwell was required and the code only enforced it once.
--
-- This is measured here as its own scenario rather than as arithmetic on F4,
-- because F4's expected settle INDEX depends on it -- the first version of this
-- file asserted 23, got 21, and the two wrong polls were the defect.
reset()
poll(true, Config.DebounceSamples)
poll(false, Config.DebounceSamples)
startedSinceDown = true
poll(true, Config.DebounceSamples - 1)
check('F4 b one hot poll is not a relight', phases(), 'RUN DOWN')
poll(true, 1)
check('F4 b the relight takes its own debounce', phases(), 'RUN DOWN UP')

-- THE SETTLE, PINNED AT BOTH ENDS. The UP poll sets settle to SettleSamples and
-- then immediately decrements it in the same call, so after the UP poll there are
-- SettleSamples - 1 polls left to count -- and the poll that reaches zero is the
-- one that answers true. Asserting the exact index rather than "it eventually
-- seals" is the difference between pinning the dwell and pinning nothing.
local at = nil
for i = 1, 200 do
\tif flowStep(true) then
\t\tat = i
\t\tbreak
\tend
end
check('F4 the settle fires on its own poll', at, Config.SettleSamples - 1)

-- ------------------------------------------------- F5 the second stall -------
-- A recovery must not pre-charge the next DOWN, and the debounce must be honoured
-- a second time in the same shift. The old code cleared `lowRun` only on its way
-- out of the UP branch, so a counter that was never reset would make the SECOND
-- recovery take effect on its first poll -- a debounce that only works once.
reset()
poll(true, Config.DebounceSamples)
poll(false, Config.DebounceSamples)
poll(true, Config.DebounceSamples)
check('F5 the first recovery is announced', phases(), 'RUN DOWN RECOVER')
poll(false, Config.DebounceSamples - 1)
check('F5 the second DOWN needs its own debounce', sawDown, false)
poll(false, 1)
check('F5 the second DOWN is a DOWN in its own right', sawDown, true)
poll(true, Config.DebounceSamples - 1)
check('F5 the second recovery keeps its debounce', phases(), 'RUN DOWN RECOVER DOWN')
poll(true, 1)
check('F5 the second recovery is announced', phases(), 'RUN DOWN RECOVER DOWN RECOVER')

-- ------------------------------------------------- F6 relight after a stall --
-- And the flag is not consumed by a recovery: a shift that stalls, recovers, and
-- is THEN relit still ends on the relight. Without the DOWN edge clearing the flag
-- this is the test that fails -- the flag set before the second DOWN would leak
-- across it and turn the next stall into a second UP.
reset()
poll(true, Config.DebounceSamples)
poll(false, Config.DebounceSamples)
poll(true, Config.DebounceSamples)
poll(false, Config.DebounceSamples)
startedSinceDown = true
poll(true, Config.DebounceSamples)
check('F6 a relight after a recovery still ends the run', phases(),
\t'RUN DOWN RECOVER DOWN UP')

-- F6 b AND A PRESS DOES NOT SURVIVE THE STALL IT PRECEDED. The click hooker sets
-- the flag UNCONDITIONALLY -- a press on StartUpLever while the core is already up
-- is recorded as a `CLICK StartUpLever` and cannot be told apart, at that moment,
-- from the first press of a start-up -- so the DOWN edge is the only thing that
-- keeps a stale press from turning the NEXT stall into a relight. Without it, a
-- shift that stalls twice ends on the first recovery for a reason nobody pressed.
reset()
poll(true, Config.DebounceSamples)
startedSinceDown = true
poll(false, Config.DebounceSamples)
poll(true, Config.DebounceSamples)
check('F6 b a press before the stall does not relight it', phases(),
\t'RUN DOWN RECOVER')

-- ------------------------------------------------------ report + exit ------
local report = table.concat(results, string.char(10))

if string.find(report, 'FAIL', 1, true) ~= nil and io ~= nil and io.stderr ~= nil then
\tio.stderr:write(report .. string.char(10))
\tos.exit(1)
end
return report
"""


def extract_flow_latches(src: str) -> str:
    """`local sawDown` through `local flowArmed`, verbatim, comments and all."""
    start = src.find("local sawDown = false")
    if start < 0:
        sys.exit("could not find the sawDown latch -- did the flow get rewritten?")
    end = src.find("local flowArmed = false", start)
    if end < 0:
        sys.exit("could not find flowArmed after sawDown")
    block = src[start:end + len("local flowArmed = false")]
    if "startedSinceDown = false" not in block:
        sys.exit("the flow latches do not declare startedSinceDown -- the relight "
                 "rule would be reading a global")
    return block


def extract_counters(src: str) -> str:
    """The countdowns, declared in the FLOW section header.

    Extracted rather than declared here because of their INITIAL VALUES: a harness
    that got `settle` starting at 1 instead of 0 would still pass every scenario
    below and would be testing a boundary the recorder does not have.
    """
    hits = re.findall(r"^local running, lowRun, lowDown, settle = .*$", src, re.M)
    if len(hits) != 1:
        sys.exit("expected exactly one flow counter declaration, found %d" % len(hits))
    if hits[0] != "local running, lowRun, lowDown, settle = false, 0, 0, 0":
        sys.exit("the flow counters changed shape: %r" % hits[0])
    return hits[0] + "\n"


def extract_flow_tail(src: str) -> str:
    """The boundary itself: the tail of `pollOnce`, from the arming test to the
    function's closing `end` (excluded, so the block can be a body here).

    The end of the block is found as the first line that is exactly `end` at column
    zero. Inside a function body every line is indented, so the first such line
    after the anchor can only be the one that closes `pollOnce` -- and the shape is
    asserted afterwards rather than trusted.
    """
    start = src.find("\tif not flowArmed then\n")
    if start < 0:
        sys.exit("could not find the flow boundary -- did pollOnce get rewritten?")
    if src.count("\tif not flowArmed then\n") != 1:
        sys.exit("the flow boundary anchor is not unique")
    end = src.find("\nend\n", start)
    if end < 0:
        sys.exit("the flow boundary is not closed by a column-zero end")
    block = src[start:end + 1]
    for needle in ("startedSinceDown", "emitPhase('RECOVER')", "Config.SettleSamples"):
        if needle not in block:
            sys.exit("the extracted flow tail is missing %r" % needle)
    if block.rstrip().splitlines()[-1].strip() != "return false":
        sys.exit("the extracted flow tail does not end in `return false`, so it "
                 "cannot be used as a function body: %r"
                 % block.rstrip().splitlines()[-1])
    for open_c, close_c in (("(", ")"), ("{", "}")):
        if block.count(open_c) != block.count(close_c):
            sys.exit("the flow tail is unbalanced on %r: %d vs %d"
                     % (open_c, block.count(open_c), block.count(close_c)))
    return block + "\n"


def extract_config(src: str) -> str:
    """The two dwells, read out of the recorder's Config table rather than copied.

    A harness that hard-codes `DebounceSamples = 3` keeps passing after the shipped
    value changes -- and passes in the direction that matters least, because its
    own scenarios use `Config.DebounceSamples` everywhere. So the numbers are read
    from the source and written into the generated Config.
    """
    want = ("DebounceSamples", "SettleSamples")
    lines = []
    for name in want:
        # The table is column-aligned, so the padding between the name and the `=`
        # is spaces rather than one -- matched loosely, pinned afterwards.
        m = re.search(r"^\t%s\s+=\s+(\d+)," % name, src, re.M)
        if not m:
            sys.exit("could not read Config.%s from the recorder" % name)
        lines.append("\t%s = %s," % (name, m.group(1)))
    return "\n".join(lines) + "\n"


def check_click_sets_the_flag(src: str) -> None:
    """A source-shape assertion, not a behavioural one, and stated as such.

    The flag is SET by the click hooker, which cannot run under Lua 5.1 without a
    mock of ClickDetector, `GetFullName` and `labels`. So what is checked here is
    that the setter is still inside the MouseClick handler and still keyed on the
    label the log prints -- the two ways this rule can be silently disconnected
    from the game. Behaviour of the boundary GIVEN the flag is what the rest of
    this file covers.
    """
    anchor = "\t\tinst.MouseClick:Connect(function()"
    if src.count(anchor) != 1:
        sys.exit("the MouseClick handler anchor occurs %d times"
                 % src.count(anchor))
    i = src.index(anchor)
    window = src[i:i + 2000]
    setter = "if name == 'StartUpLever' then startedSinceDown = true end"
    if window.count(setter) != 1:
        sys.exit("the click hooker no longer sets startedSinceDown on StartUpLever "
                 "-- the relight rule can never become true in the game")
    closer = window.find("\n\t\tend)")
    if closer < 0:
        sys.exit("could not find the end of the MouseClick handler")
    if window.index(setter) > closer:
        sys.exit("the setter is outside the MouseClick handler body")


def main() -> int:
    src = RECORDER.read_text(encoding="utf-8")
    latches = extract_flow_latches(src)
    counters = extract_counters(src)
    tail = extract_flow_tail(src)
    config = extract_config(src)
    check_click_sets_the_flag(src)

    # HEAD opens the Config table and the builder closes it: the table's CONTENTS
    # come from the recorder, its braces are this file's syntax.
    body = (
        HEAD + config + "}\n" + PHASE_STUB + "\n" + latches + "\n" + counters + "\n"
        + "local function flowStep(isRunning)\n" + tail + "end\n" + TAIL
    )
    OUT.write_text(body, encoding="utf-8", newline="\n")
    raw = OUT.read_bytes()
    print("wrote %s" % OUT)
    print("  lines %d  bytes %d" % (raw.decode("utf-8").count("\n"), len(raw)))
    print("  extracted: latches %d, counters %d, boundary %d lines"
          % (latches.count("\n") + 1, counters.count("\n"), tail.count("\n")))
    print("  backslash bytes %d  (must be 0: the editor decodes escapes once)"
          % raw.count(0x5C))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
