"""Build a harness for THE CORE GATE: what the recorder refuses to write, and when.

WHY THIS EXISTS. The operator's rule for the recorder (2026-09-30) is
"注入后立刻开始（注意在核心完全开启前不要采集温度、压力等）" -- start at once, but do
not collect temperature and pressure before the core is fully on. The gate that
implements it is new code in a file that is injected into a game he can start
ONCE per shift, so a green harness before the injection is the whole of the
evidence available. That is the same argument run_tests.sh makes about the
watcher and the player-GUI reader, and it applies here word for word.

WHAT IS EXTRACTED, and why it is two regions rather than one. The gate itself
(`coreLive`, `coreGateOpen`, `isCoreStat`) is declared in the READERS section,
and the code that ACTS on it is inside `readStats`, eight hundred lines later.
A test that copied either half would agree with a version of the recorder that
does not ship, so both halves are lifted out of the shipped file by text and
stitched in their original order. `readStats` is extracted whole rather than as
a fragment of its loop, because the loop's other work -- the STATADD/STATDEL
bookkeeping -- is part of what the gate must not break.

THE ONE CHECK HERE THAT MATTERS MOST is `the held value is not in `last``. The
gate has to HOLD a reading rather than filter it, and the difference is
invisible in the output file: an implementation that wrote the pre-boot zero
into `last` and then declined to emit would produce exactly the same lines as
one that never looked at the value, right up until the ignition poll arrives
carrying a value equal to the pre-boot one -- at which point the filtered
version sees "no change" and the ignition is never reported at all. That is a
silent, plausible, one-line mistake, which is what this file is for.

    python _tools/build_gate_test.py
    /d/Lua/5.1/lua.exe -e "print(assert(loadfile('_tools/_gate_states.luau'))())"

The generated _gate_states.luau is NOT the source of truth -- edit this file.
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
RECORDER = ROOT / "TRG_original_recorder.luau"
OUT = ROOT / "_gate_states.luau"

# The two regions, by their exact opening line. Both were read off the shipped
# recorder; a mismatch here means the recorder moved and this builder has to be
# re-pointed rather than silently extracting the wrong function.
#
# The gate anchor stops at the NAME and does not carry `= false`. An anchor that
# included the initial value would make this builder fail to BUILD when that value
# changes, and a builder refusing to build is not the harness catching anything --
# selftest_gate_test.py's "the gate defaults to OPEN" mutation was reported as
# "red, but not on the check that guards it" for exactly that reason.
GATE_OPEN = "local coreLive"
STATS_OPEN = "local function readStats()"


def block_from(text: str, opening: str, what: str) -> str:
    """Slice from `opening` to the first following line that is exactly `end`.

    By INDENTATION, not by counting `function`/`end` tokens, and the first
    attempt here is the reason: a token counter that decrements on every `end`
    walks straight past the one-line `if ... then ... end` inside `readStats` and
    cuts the function open. Distinguishing an `if`'s `end` from a function's
    needs a real parser.

    Indentation is enough because the shipped recorder is consistently indented
    and every top-level block closes with an unindented `end` -- and this does
    not ASSUME that: the caller asserts on tokens that must be present in the
    slice, so a slice that stopped early fails loudly instead of producing a
    harness that tests half a function and passes.
    """
    i = text.find(opening)
    if i < 0:
        sys.exit("extraction: %r not found in %s" % (opening, RECORDER.name))
    if text.find(opening, i + 1) >= 0:
        sys.exit("extraction: %r appears more than once -- the anchor is not unique"
                 % opening)

    j = i
    while True:
        nl = text.find("\n", j)
        if nl < 0:
            sys.exit("extraction: %s never closed -- no unindented `end` to EOF" % what)
        line = text[j:nl]
        if line == "end":
            return text[i:nl]
        j = nl + 1


HEAD = """--!nocheck
-- GENERATED by _tools/build_gate_test.py -- edit that file, not this one.
--
-- THE CORE GATE and the stats scan it gates are EXTRACTED from
-- _tools/TRG_original_recorder.luau. Everything else is mock: no Roblox API and
-- no DataModel instance is touched.

local results = {}
local function say(s) results[#results + 1] = tostring(s) end

local function check(name, got, want)
\tlocal ok = (got == want)
\tsay((ok and 'PASS ' or 'FAIL ') .. name)
\tif not ok then
\t\tsay('     got  [' .. tostring(got) .. ']')
\t\tsay('     want [' .. tostring(want) .. ']')
\tend
end

local function checkTrue(name, cond, why)
\tsay((cond and 'PASS ' or 'FAIL ') .. name)
\tif not cond then say('     ' .. why) end
end

-- ============================ THE MOCK PLANT ==============================
-- A ValueObject is anything with a Name, a Value and `IsA('ValueBase')` true.
-- A container answers `GetChildren` and `FindFirstChild`. That is the whole of
-- the surface the extracted code touches, which is itself worth stating: if the
-- recorder ever reaches for a third method, this harness stops compiling rather
-- than quietly testing something else.
local function mkValue(name, value)
\treturn {
\t\tName = name,
\t\tValue = value,
\t\tIsA = function(self, c) return c == 'ValueBase' end,
\t\tGetChildren = function(self) return {} end,
\t}
end

local function mkOther(name)
\t-- Present, named, and deliberately NOT a ValueObject: the recorder has to
\t-- tolerate this without raising, because
\t-- `MainData:FindFirstChild('GameActive').Value` on a Folder is exactly the
\t-- crash that would take the whole recording with it.
\t--
\t-- The __index that RAISES is the whole of the mock's fidelity, and it was
\t-- added because its absence hid a mutation. Without it, `flag.Value` on this
\t-- table answers nil -- so a recorder that dropped the `IsA('ValueBase')` guard
\t-- sailed through `if flag.Value ~= true then return false end` and the harness
\t-- called the crash-free path correct. Roblox does not answer nil there: it
\t-- raises "Value is not a valid member of Folder", inside the poll, on the first
\t-- poll, with no receipt. A generous stub is a stub that hides a crash.
\treturn setmetatable({
\t\tName = name,
\t\tIsA = function(self, c) return false end,
\t\tGetChildren = function(self) return {} end,
\t}, {
\t\t__index = function(_, key)
\t\t\terror(key .. ' is not a valid member of Folder', 2)
\t\tend,
\t})
end

local function mkFolder(name, kids)
\treturn {
\t\tName = name,
\t\tIsA = function(self, c) return false end,
\t\tGetChildren = function(self) return kids end,
\t\tFindFirstChild = function(self, n)
\t\t\tfor _, k in ipairs(kids) do
\t\t\t\tif k.Name == n then return k end
\t\t\tend
\t\t\treturn nil
\t\tend,
\t}
end

-- ============================ THE HARNESS WIRING ==========================
-- `put` / `putText` are the recorder's two writers; here they are recorders
-- themselves. `last` is the change detector the gate has to keep its hands off,
-- and `statsSeen` is the manifest the STATADD/STATDEL bookkeeping is built from.
local wrote, texts, events = {}, {}, {}
local last, statsSeen, changed = {}, {}, {}

local function put(key, value)
\t-- Modelled on the shipped `put`: it is change-gated, so the same value twice
\t-- is one write. Reproduced here because the gate's whole failure mode is a
\t-- value that was written once too often, and a mock that recorded every call
\t-- would hide it.
\tif last[key] == value then return end
\tlast[key] = value
\twrote[#wrote + 1] = key .. '=' .. tostring(value)
end

local function putText(key, text)
\tif text == nil then return end
\tif last[key] == text then return end
\tlast[key] = text
\ttexts[#texts + 1] = key .. ' ' .. tostring(text)
end

local function emitEvt(kind, rest) events[#events + 1] = kind .. ' ' .. tostring(rest) end

local Stats -- the mock Workspace.Stats, reassigned by each scenario
local Workspace = {
\tFindFirstChild = function(self, n)
\t\tif n == 'Stats' then return Stats end
\t\treturn nil
\tend,
}
local MainData = nil

-- `keys` and `has` read the recording tables, so they belong up here with them.
local function keys(n) return table.concat(wrote, ' ') end

local function has(list, needle)
\tfor _, s in ipairs(list) do
\t\tif s == needle then return true end
\tend
\treturn false
end
"""

TAIL = """
-- ---------------------------------------------------------------- helpers --
-- `reset` is defined HERE, below the extracted gate, and that placement is
-- load-bearing rather than tidy. It used to sit above it, where `coreLive` is not
-- yet in scope -- so `coreLive = false` was a write to a GLOBAL while the gate
-- read its own LOCAL of the same name, the latch was never cleared between
-- scenarios, and G5/G7/G9/G10 failed against a recorder that was correct. A
-- harness whose reset silently does nothing is a harness that reports the state
-- left by whichever scenario ran last.
local function reset()
\tStats = mkFolder('Stats', {})
\tMainData = nil
\twrote, texts, events = {}, {}, {}
\tlast, statsSeen, changed = {}, {}, {}
\tcoreLive = false
end

-- ===================== G1 the gate does not open on a guess =================
-- Three ways the flag can fail to be the flag, and all three must leave the gate
-- closed. `false` is the real one on a cold reactor; the other two are the ones a
-- NameError would be caught by in a real run, and catching them here is what says
-- the gate cannot take the recorder down with it.

reset()
Stats = mkFolder('Stats', { mkValue('GameActive', false) })
MainData = Workspace:FindFirstChild('Stats')
coreGateOpen()
check('G1 a false flag leaves the gate closed', coreLive, false)

reset()
Stats = mkFolder('Stats', {})
MainData = Workspace:FindFirstChild('Stats')
coreGateOpen()
check('G1 a MISSING flag leaves the gate closed', coreLive, false)

reset()
Stats = mkFolder('Stats', { mkOther('GameActive') })
MainData = Workspace:FindFirstChild('Stats')
local okCall = pcall(coreGateOpen)
check('G1 a same-named NON-ValueObject is survived', okCall, true)
check('G1 and it leaves the gate closed', coreLive, false)

reset()
Stats = mkFolder('Stats', { mkValue('GameActive', true) })
MainData = Workspace:FindFirstChild('Stats')
check('G1 a true flag opens it', coreGateOpen(), true)
check('G1 and the state says so too', coreLive, true)

-- ===================== G2 the gate LATCHES =================================
-- Not an optimisation: the cold-trip arm reads `m.temp` below LowTripF AFTER the
-- shutdown, so a gate that reopened when GameActive went false would silence the
-- readings the seal rule is made of.

reset()
Stats = mkFolder('Stats', { mkValue('GameActive', true) })
MainData = Workspace:FindFirstChild('Stats')
coreGateOpen()
Stats = mkFolder('Stats', { mkValue('GameActive', false) })
MainData = Workspace:FindFirstChild('Stats')
check('G2 the gate stays open when the flag goes back to false', coreGateOpen(), true)
check('G2 and coreLive is not reset either', coreLive, true)

-- ===================== G3 what counts as a core reading ====================
-- The container and its children, and nothing that merely starts with the same
-- letters -- `CoreStuff` and `Reactor.Core` are the two near-misses a prefix test
-- written carelessly would swallow.

check('G3 the container itself is a core stat', isCoreStat('Core'), true)
check('G3 a child of it is one', isCoreStat('Core.TemperatureVal'), true)
check('G3 a deeper child is one too', isCoreStat('Core.A.B'), true)
check('G3 a longer name is NOT', isCoreStat('CoreStuff'), false)
check('G3 a name that ends in Core is NOT', isCoreStat('Reactor.Core'), false)
check('G3 a prefix of the name is NOT', isCoreStat('Cor'), false)
check('G3 an unrelated stat is NOT', isCoreStat('GameActive'), false)

-- ===================== G4 held means NOT WRITTEN ===========================
-- The check this file exists for. A closed gate must leave the value out of
-- `last` entirely, or the ignition is swallowed on the poll it happens.

reset()
Stats = mkFolder('Stats', {
	mkValue('GameActive', false),
	mkValue('ActiveQPUs', 4),
	mkFolder('Core', { mkValue('TemperatureVal', 0), mkValue('PressureVal', 20) }),
})
MainData = Workspace:FindFirstChild('Stats')
readStats()

checkTrue('G4 the core temperature is not written while the gate is closed',
	not has(wrote, 's.Core.TemperatureVal=0'), 'wrote: ' .. keys(0))
checkTrue('G4 the core pressure is not either',
	not has(wrote, 's.Core.PressureVal=20'), 'wrote: ' .. keys(0))
check('G4 and it is NOT sitting in `last` as an unknown-key marker',
	last['s.Core.TemperatureVal'], nil)

-- The other half of the same rule, and the half that is easy to throw away by
-- accident: everything OUTSIDE Core still has to be written, because that is
-- where the boot sequence itself is recorded.
checkTrue('G4 a non-core stat IS still written',
	has(wrote, 's.ActiveQPUs=4'), 'wrote: ' .. keys(0))
checkTrue('G4 and so is the flag the gate reads',
	has(wrote, 's.GameActive=false'), 'wrote: ' .. keys(0))

-- ===================== G5 the ignition arrives as a NEW key ================
-- The same reading, the same value, before and after -- and it must still be
-- written, because the closed poll never put it in `last`. A "filter, don't hold"
-- implementation fails here and nowhere else.

reset()
Stats = mkFolder('Stats', {
	mkValue('GameActive', false),
	mkFolder('Core', { mkValue('TemperatureVal', 0) }),
})
MainData = Workspace:FindFirstChild('Stats')
readStats()
checkTrue('G5 the pre-boot poll wrote nothing about the core',
	not has(wrote, 's.Core.TemperatureVal=0'), 'wrote: ' .. keys(0))

Stats = mkFolder('Stats', {
	mkValue('GameActive', true),
	mkFolder('Core', { mkValue('TemperatureVal', 0) }),
})
MainData = Workspace:FindFirstChild('Stats')
readStats()
checkTrue('G5 the SAME value is written once the gate opens',
	has(wrote, 's.Core.TemperatureVal=0'), 'wrote: ' .. keys(0))
check('G5 and it is now in `last` for the next change to compare against',
	last['s.Core.TemperatureVal'], 0)

-- ===================== G6 the gate opens from the stats scan alone =========
-- `pollOnce` runs readReactor first, so in the shipped loop the gate is already
-- open by the time readStats runs. The claim here is that readStats does not
-- DEPEND on that: it calls the gate itself, and a reader that only ran the scan
-- still gets the core readings.

reset()
Stats = mkFolder('Stats', {
	mkValue('GameActive', true),
	mkFolder('Core', { mkValue('TemperatureVal', 9420) }),
})
MainData = Workspace:FindFirstChild('Stats')
readStats()
check('G6 readStats opens the gate by itself', coreLive, true)
checkTrue('G6 and writes the core reading in the same poll',
	has(wrote, 's.Core.TemperatureVal=9420'), 'wrote: ' .. keys(0))

-- ===================== G7 the announcement fires ONCE ======================
-- A COREGATE line per poll would be two thousand lines of noise in a file whose
-- whole design is that a line means something changed.

reset()
Stats = mkFolder('Stats', {
	mkValue('GameActive', true),
	mkFolder('Core', { mkValue('TemperatureVal', 100) }),
})
MainData = Workspace:FindFirstChild('Stats')
readStats(); readStats(); readStats()
local n = 0
for _, e in ipairs(events) do
	if string.sub(e, 1, 8) == 'COREGATE' then n = n + 1 end
end
check('G7 COREGATE is announced exactly once', n, 1)

-- ===================== G8 the manifest still sees a held key ===============
-- The gate holds the VALUE, not the KEY. `seen` is filled before the gate is
-- consulted, so a held-back path is still part of the manifest -- which is what
-- keeps the STATDEL sweep from announcing that the whole Core container
-- disappeared on the poll before the gate opened.

reset()
Stats = mkFolder('Stats', {
	mkValue('GameActive', false),
	mkFolder('Core', { mkValue('TemperatureVal', 0) }),
})
MainData = Workspace:FindFirstChild('Stats')
readStats()
check('G8 the held path is in statsSeen', statsSeen['Core.TemperatureVal'], true)
local del = false
for _, e in ipairs(events) do
	if string.sub(e, 1, 8) == 'STATDEL ' then del = true end
end
check('G8 and nothing was announced as deleted', del, false)

-- ===================== G9 a string under Core is held too ==================
-- `putText` is a second writer with its own path through the gate, and a gate
-- that only covered `put` would let the pre-boot error text out.

reset()
Stats = mkFolder('Stats', {
	mkValue('GameActive', false),
	mkFolder('Core', { mkValue('Status', 'STANDBY') }),
})
MainData = Workspace:FindFirstChild('Stats')
readStats()
check('G9 the core string is held back', #texts, 0)

Stats = mkFolder('Stats', {
	mkValue('GameActive', true),
	mkFolder('Core', { mkValue('Status', 'STANDBY') }),
})
MainData = Workspace:FindFirstChild('Stats')
readStats()
check('G9 and written once the gate opens', texts[1], 's.Core.Status STANDBY')

-- ===================== G10 the gate reads Stats FRESH ======================
-- `MainData` is captured once at load time and re-fetched if it is nil. A Stats
-- folder that did not exist when the recorder was injected has to be picked up,
-- or the gate would stay shut for the whole run on a shift that starts early.

reset()
Stats = nil
MainData = nil
check('G10 a missing Stats folder is not fatal and not open', coreGateOpen(), false)

Stats = mkFolder('Stats', { mkValue('GameActive', true) })
check('G10 the gate opens once the folder appears', coreGateOpen(), true)

-- ------------------------------------------------------ report + exit ------
-- The exit is not decoration: run_tests.sh and selftest_gate_test.py both gate on
-- the process code, and a chunk that returns a report full of FAILs while exiting
-- 0 reads as green to every caller. (The first version of this harness did exactly
-- that, which made the mutation run report "stayed GREEN" for six mutations that
-- did in fact turn it red. A suite whose failure is invisible to `$?` is only
-- half a suite.)
local report = table.concat(results, string.char(10))

if string.find(report, 'FAIL', 1, true) ~= nil and io ~= nil and io.stderr ~= nil then
	io.stderr:write(report .. string.char(10))
	os.exit(1)
end
return report
"""


def main() -> int:
    text = RECORDER.read_bytes().decode("utf-8")

    # The gate region opens with a plain `local`, not with a `function`, so
    # `block_from` cannot slice it on its own -- it would stop at the end of the
    # first function it found, which is `coreGateOpen`, and leave `isCoreStat`
    # behind. The slice is therefore taken from the declaration down to the end of
    # the LAST function in the region, which is found by slicing that function
    # first and then widening back to the declaration.
    is_core = block_from(text, "local function isCoreStat(path)", "isCoreStat")
    head = text.find(GATE_OPEN)
    if head < 0:
        sys.exit("extraction: %r not found" % GATE_OPEN)
    tail = text.find(is_core)
    if tail < head:
        sys.exit("extraction: isCoreStat sits ABOVE the gate declaration -- the "
                 "regions are in the wrong order and this builder is stale")
    gate = text[head:tail + len(is_core)]

    stats = block_from(text, STATS_OPEN, "readStats")

    # What these tokens prove is that the SLICE is complete, not what the sliced
    # code says. `local coreLive = false` used to be the first of them, and it was
    # the wrong shape of assertion: pinning the initial value here makes this
    # builder a second copy of the recorder's behaviour, and it turned
    # selftest_gate_test.py's "the gate defaults to OPEN" mutation red as a
    # BUILD failure instead of a check failure -- the builder refusing to build is
    # not the harness catching anything. The declaration is what the slice has to
    # contain.
    for token in ("local coreLive", "local function coreGateOpen()",
                  "local function isCoreStat(path)", "return path == 'Core'"):
        if token not in gate:
            sys.exit("gate region is missing %r -- the slice is incomplete" % token)
    if "local function readReactor()" in gate:
        sys.exit("gate region ran past its end and swallowed readReactor")

    for token in ("local function readStats()", "if coreLive or not isCoreStat(path) then",
                  "statsSeen = seen"):
        if token not in stats:
            sys.exit("readStats region is missing %r" % token)

    body = HEAD + "\n-- ============ EXTRACTED: THE CORE GATE (shipped bytes) ============\n" \
        + gate + "\n\n-- ============ EXTRACTED: readStats (shipped bytes) ===============\n" \
        + stats + "\n" + TAIL

    if "\r" in body:
        sys.exit("generated harness has CR in it")

    OUT.write_bytes(body.encode("utf-8"))
    print("wrote %s: %d bytes, %d lines" % (OUT, len(body.encode("utf-8")),
                                            body.count("\n") + 1))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
