# -*- coding: utf-8 -*-
"""Pin d7's two new subjects by running the shipped bytes: the click primitive
and the seq floor.

SUBJECT 1 -- clickScreen().  d1..d4 pressed by ARITHMETIC: they computed a point
and handed it straight to VirtualInputManager.  Every one of those presses
landed 58 px above its target and the symptom was nothing at all.  The recipe
that actually lit this reactor (Phase 106/107) never did that: it MOVED, then
asked the engine where the mouse ended up, then clicked THERE.  So the property
to pin is not "the point is right" -- that is the arithmetic again -- it is
"the point that gets clicked is the one the engine reported, and a bad move or
an unreadable location fires NO button event at all".

SUBJECT 2 -- the seq floor.  Measured 2026-10-10: the executor's own state file
held 203 while the very next read of it returned 0.  runCmds saw last = 0,
re-ran the entire file, and re-ran the `stop` in it -- which is how a replay
reached the session-ender.  Memory cannot lag, so the floor is now kept in both
places and the higher one wins.  The case that matters is not "the floor is
read", it is "an empty read does NOT replay".

WHY THE SUBJECTS ARE EXTRACTED BY TEXT.  Same contract as the recorder suites:
a re-typed copy keeps passing after the shipped one changes, which is exactly
the drift this file exists to catch.

Run:  python _tools/build_drive_route_test.py [source.luau] [out.luau]
The path arguments exist so selftest_drive_route.py can point this same
extraction at a deliberately broken copy.
"""

import hashlib
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
DRIVE = ROOT / "TRG_original_drive.luau"
OUT = ROOT / "_drive_route_states.luau"

HEAD = """--!nocheck
-- GENERATED by _tools/build_drive_route_test.py -- edit that file, not this one.
-- clickScreen(), loadSeq(), saveSeq() and runCmds() below are EXTRACTED from
-- _tools/TRG_original_drive.luau by text and run under a stub engine.  No Roblox
-- API is touched; see the builder for why.

local results = {}
local function say(s) results[#results + 1] = tostring(s) end

local function check(name, got, want)
  local ok = (got == want)
  say((ok and 'PASS ' or 'FAIL ') .. name)
  if not ok then
    say('     got  [' .. tostring(got) .. ']')
    say('     want [' .. tostring(want) .. ']')
  end
end

-- ============================== STUB ENGINE ===============================
-- The stub RECORDS what it was handed.  That is the whole measurement: the
-- claim under test is about which point is passed to the button event, so a
-- stub that only returned success would be measuring nothing.

local calls = {}
local mouseLoc = { X = 0, Y = 0 }
local mouseErr = nil
local moveErr = nil

local VIM = {}
function VIM:SendMouseMoveEvent(gx, gy, g)
  if moveErr ~= nil then error(moveErr, 2) end
  calls[#calls + 1] = 'move ' .. tostring(gx) .. ',' .. tostring(gy)
end
function VIM:SendMouseButtonEvent(x, y, b, down, g, i)
  calls[#calls + 1] = (down and 'down ' or 'up ') .. tostring(x) .. ',' .. tostring(y)
end

local UIS = {}
function UIS:GetMouseLocation()
  if mouseErr ~= nil then error(mouseErr, 2) end
  return mouseLoc
end

local game = {}
function game:GetService(name)
  if name == 'VirtualInputManager' then return VIM end
  if name == 'UserInputService' then return UIS end
  error('unexpected service: ' .. tostring(name))
end

-- wait() is counted, not slept: a case asserts the read happens AFTER the move,
-- and on a stub the only thing separating the two is the call to this function.
local waits = 0
local task = {}
function task.wait(t) waits = waits + 1 end

local NL = string.char(10)
local CR = string.char(13)

local files = {}
local function read(p) return files[p] or '' end
local function write(p, s) files[p] = s end
local CFG = { CmdFile = 'cmd', StateFile = 'state' }

local ran = {}
local function execute(seq, rest) ran[#ran + 1] = seq end

local M = {}

-- ============================== SUBJECTS =================================
"""

TAIL = """
-- ======================= CASES: the click primitive ======================
local function obsClick(gx, gy, ret)
  calls = {}
  waits = 0
  mouseLoc = ret
  mouseErr = nil
  moveErr = nil
  local how, err = clickScreen(gx, gy)
  return tostring(how) .. ' | ' .. table.concat(calls, ' ') .. ' | waits=' .. tostring(waits)
end

-- R1 is the defect.  The move is given the guess (1109,614) and the engine
-- answers (1109,673); the button must be handed 673.  d4 handed it 614 -- the
-- argument, not the answer -- and that is the 58 px, stated as a case.
check('R1 the button is handed the ENGINE-REPORTED point, not the argument',
  obsClick(1109, 614, { X = 1109, Y = 673 }),
  'mouse@1109,673 | move 1109,614 down 1109,673 up 1109,673 | waits=2')

-- R2: the read must come after the move.  The queue is not instant, so a read
-- taken in the same call as the move returns the PREVIOUS position -- the real
-- failure mode this ordering exists for.
check('R2 the location is read AFTER the move, not in the same call',
  obsClick(1109, 614, { X = 1109, Y = 673 }),
  'mouse@1109,673 | move 1109,614 down 1109,673 up 1109,673 | waits=2')

-- R3: fractional read-back is floored, not rounded.  SendMouseButtonEvent takes
-- integers; a .5 that rounds up is a different pixel, and 2026-10-09 the driver
-- already paid for a rounded half once (C10 next door).
check('R3 a fractional read-back is FLOORED, not rounded',
  obsClick(100, 200, { X = 1109.9, Y = 673.9 }),
  'mouse@1109,673 | move 100,200 down 1109,673 up 1109,673 | waits=2')

-- R4: no read-back, no click.  A nil location must NOT fall through to the
-- argument -- that would be the old arithmetic wearing the new name.
check('R4 an unreadable location fires NO button event',
  obsClick(100, 200, nil),
  'nil | move 100,200 | waits=1')

-- R5: an unreadable location that RAISES is the same answer, named.
check('R5 a raising location is reported, and still fires no button event',
  (function()
    calls = {}
    waits = 0
    moveErr = nil
    mouseErr = 'GetMouseLocation is not a valid member'
    local how, err = clickScreen(100, 200)
    return tostring(err) .. ' | ' .. table.concat(calls, ' ')
  end)(),
  'ERR GetMouseLocation | move 100,200')

-- R6: a refused move is named, and nothing else runs.
check('R6 a refused move is named and stops the press',
  (function()
    calls = {}
    waits = 0
    mouseErr = nil
    moveErr = 'SendMouseMoveEvent refused'
    local how, err = clickScreen(100, 200)
    return tostring(err) .. ' | ' .. table.concat(calls, ' ') .. ' | waits=' .. tostring(waits)
  end)(),
  'ERR SendMouseMoveEvent |  | waits=0')

-- R7: a press at the origin is still a press.  A truthiness guard that dropped
-- a legitimate 0 would make the top-left corner unclickable, and nothing else
-- here would notice.
check('R7 a legitimate 0,0 read-back is not mistaken for a failure',
  obsClick(5, 5, { X = 0, Y = 0 }),
  'mouse@0,0 | move 5,5 down 0,0 up 0,0 | waits=2')

-- ======================= CASES: the seq floor ========================
-- The observation is the LIST OF SEQS THAT RAN.  Nothing else in this file can
-- distinguish "did not replay" from "replayed and I did not look".
local function obsRun(cmd, state, mem)
  files['cmd'] = cmd or ''
  files['state'] = state or ''
  M._seq = mem
  ran = {}
  runCmds()
  return table.concat(ran, ',')
end

local function cmdOf(...)
  local t = {}
  for _, s in ipairs({ ... }) do t[#t + 1] = s end
  return table.concat(t, NL) .. NL
end

-- S1 is the replay, in two steps.  Step one is ordinary.  Step two is the day
-- the executor forgot to flush: the state file reads back empty even though a
-- seq was written, and the ONLY thing standing between that and a full replay
-- is the floor kept in memory.
files['state'] = ''
M._seq = nil
files['cmd'] = cmdOf('1 a', '2 b', '3 c')
ran = {}
runCmds()
check('S1a a fresh run with no state file executes the file and forgets nothing',
  table.concat(ran, ','), '1,2,3')
files['state'] = ''
files['cmd'] = cmdOf('1 a', '2 b', '3 c', '4 d')
ran = {}
runCmds()
check('S1b an EMPTY read after a write does NOT replay -- only 4 runs',
  table.concat(ran, ','), '4')

check('S2 the in-memory floor wins when it is higher than the file',
  obsRun(cmdOf('1 a', '2 b', '5 e', '6 f'), '', 300), '')

check('S3 a lower floor does not suppress real commands',
  obsRun(cmdOf('1 a', '2 b', '5 e', '6 f'), 5, nil), '6')

-- S4: the floor is a FLOOR.  Writing a smaller seq must not lower it, or a
-- command that finished out of order could re-open already-run seqs.
files['state'] = ''
M._seq = nil
saveSeq(9)
saveSeq(2)
check('S4 writing a smaller seq does not lower the floor',
  tostring(M._seq) .. ' state=' .. tostring(files['state']), '9 state=2' .. NL)

check('S5 a command exactly at the floor does not run again',
  obsRun(cmdOf('1 a', '2 b', '3 c'), 3, nil), '')

check('S6 commands are executed in file order',
  obsRun(cmdOf('7 g', '8 h', '9 i'), 6, nil), '7,8,9')

-- S7: a pass with NOTHING NEW still has to raise the floor, and this is the
-- hole the other seq cases cannot see.  S1b gets its floor from a pass that
-- ran something, so saveSeq did the raising there.  The dangerous pass is the
-- quiet one -- nothing above the floor -- because it leaves the memory floor
-- unarmed, and the very next pass is the laggy read it exists to cover.
-- Observed as a compound on purpose: what the floor BECAME, and what the
-- following laggy read then ran.  Either half alone can be true by accident.
files['state'] = '3' .. NL
M._seq = nil
files['cmd'] = cmdOf('1 a', '2 b', '3 c')
ran = {}
runCmds()
local armed = tostring(M._seq)
files['state'] = ''          -- the measured lag, one read later
files['cmd'] = cmdOf('1 a', '2 b', '3 c', '4 d')
ran = {}
runCmds()
check('S7 a pass with nothing new still arms the floor',
  armed .. ' then ' .. table.concat(ran, ','), '3 then 4')

-- ============================== REPORT ===================================
-- Printed, not just counted.  A harness that collects results and never writes
-- them out is "all green" and "never ran" in the same bytes -- and this suite
-- exists because a green run has already been the misleading observation once.
-- The verdict is ALSO carried in the exit code, so a caller that only looks at
-- rc cannot mistake a crash for a pass.
local bad = 0
for _, r in ipairs(results) do
  if string.sub(r, 1, 4) == 'FAIL' then bad = bad + 1 end
  io.write(r .. NL)
end
io.write('CHECK ' .. tostring(#results) .. ' ok, ' .. tostring(bad) .. ' failed' .. NL)
io.write('VERDICT ' .. (bad == 0 and 'PASS' or 'FAIL') .. NL)
os.exit(bad == 0 and 0 or 1)
"""


def _grab(src, name, kind="function"):
    """Return the text of `local function NAME(...)` up to its closing `end`."""
    start = src.find("local function %s(" % name)
    if start < 0:
        sys.exit("the driver no longer contains local function %s -- this "
                 "harness would be testing a function that is not there" % name)
    lines = src[start:].split("\n")
    out = [lines[0]]
    for ln in lines[1:]:
        out.append(ln)
        if ln == "end":
            break
    else:
        sys.exit("could not find the closing end of %s" % name)
    return "\n".join(out)


def main(argv):
    src_path = Path(argv[1]) if len(argv) > 1 else DRIVE
    out_path = Path(argv[2]) if len(argv) > 2 else OUT
    src = src_path.read_text(encoding="utf-8")

    # The invariant, stated where it can be enforced: there is exactly ONE place
    # in the driver that clicks a pixel.  A second SendMouseButtonEvent call site
    # is a second copy of the conversion, and copies drift.
    # Counted as CALL SITES ("vim:Name("), not as substrings: the doc comments
    # above the primitive name both methods, and a count that includes prose
    # would go red the moment someone explained the code better.
    buttons = src.count("vim:SendMouseButtonEvent(")
    if buttons != 2:
        sys.exit("the two button events (down, up) must be the ONLY ones; "
                 "found %d call sites" % buttons)
    movers = src.count("vim:SendMouseMoveEvent(")
    if movers != 1:
        sys.exit("there must be exactly one move call site; found %d" % movers)

    for needle in ("UIS", "GetMouseLocation", "loadSeq", "saveSeq", "M._seq"):
        if needle == "UIS":
            if "GetMouseLocation" not in src:
                sys.exit("GetMouseLocation is gone from the driver")
            continue
        if needle not in src:
            sys.exit("the driver no longer contains %r" % needle)

    parts = [
        _grab(src, "clickScreen"),
        _grab(src, "loadSeq"),
        _grab(src, "saveSeq"),
        _grab(src, "runCmds"),
    ]

    body = HEAD + "\n".join(parts) + "\n" + TAIL
    out_path.write_text(body, encoding="utf-8", newline="\n")

    raw = out_path.read_bytes()
    print("wrote %s" % out_path.name)
    print("source %s  sha256 %s" % (src_path.name,
                                    hashlib.sha256(src.encode("utf-8")).hexdigest()[:16]))
    print("lines %d  bytes %d" % (body.count("\n") + 1, len(raw)))
    print("extracted %d line(s) across %d subjects"
          % (sum(p.count("\n") for p in parts), len(parts)))
    print("cases %d" % body.count("check('"))
    print("backslash bytes %d  (must be 0: the editor decodes escapes once)"
          % raw.count(b"\\"))
    print("crlf bytes %d" % raw.count(b"\r\n"))
    if raw.count(b"\\") != 0:
        sys.exit("the generated harness contains a backslash byte")
    if raw.count(b"\r\n") != 0:
        sys.exit("the generated harness contains CRLF")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
