"""Build a harness that runs the SHIPPED driveStep against a simulated core.

Why a builder and not a hand-written test file: a test that is a COPY of the
function under test passes against the copy, which is the one version that is
never the one that ships. This extracts `driveStep` out of
_tools/TRG_original_recorder.luau by text, wraps it in mocks, and prints the
result -- so what runs is the same bytes that get injected, and a change to the
recorder is a change to the test.

    python _tools/build_driver_test.py
    # writes _tools/_driver_states.luau, then run it:
    #   in Studio, execute_luau the file contents; or read it and run it anywhere
    #   Luau runs, because the harness touches no Roblox API at all.

THE SCENARIOS RUN IN BOTH CONFIGURATIONS, AND THAT IS THE POINT. `D7` has the
operator pressing the shutdown lever himself (`D7: 我自己手动关`), so the LIVE
setting is `Config.DrivePressControls = false` and the driver never presses
anything. The press path is not deleted -- §1.4 forbids removing a capability
without a replacement -- so it stays in the shipped function behind that flag,
and a scenario opts into it with `{ pressControls = true }`. Every scenario
below therefore states which configuration it is about, and the suite covers
both rather than the one that happens to be shipping.

The scenarios are the ways the driver can end, and every one of them is a path
out of the state machine, because a state machine is only as good as its exits:

  S1  hot core, driver holds the controls -> presses, ends `shut_down`   (press)
  S2  hot core, the shut switch INERT     -> one press, ends `shut_down` (press)
  S3  cold core, driver holds the controls-> lights it, ends `shut_down` (press)
  S4  no temperature readout at all       -> presses nothing, stays `arming`
  S5  cold at inject, operator lights it  -> waits, then ends `watching` (live)
  S6  the core dips on its own mid-hold   -> one press, ends `shut_down` (press)
  S7  a slow loop is measured, not assumed-> the press lands on time     (press)
  S8  a slow FIRST poll fakes nothing     -> one press, ends `shut_down` (press)
  S9  the operator presses, game confirms -> ends `shut-confirmed`      (live)
  S10 hot core at inject, no press ever   -> stays `watching`, nothing pressed
  S11 the MACHINE ROOM melts down         -> names it, nothing pressed  (live)

Two of these are scars. S3 found a real bug on 2026-09-26: with the core cold at
inject, the driver lit it and then parked in `waiting_up` waiting for a `sawDown`
the cold path never produces, so the run would have recorded a healthy reactor
until the sample cap instead of the flow it was injected for. The fix then was
to light the core earlier; under the live setting it is not lit at all, because
the operator does that himself and the core can only be switched ONCE.

S2 is the other scar, and it is a scar about retries. The driver used to walk
down its candidate list, pressing the next switch whenever a press proved inert,
so S2 used to expect two presses. With one attempt available, a second press is
a second spent action, and the run now ends naming the control it pressed. The
scenario is kept precisely because it pins that: `ShutFallback` is on the list,
it is never pressed, and a driver that starts walking again fails here.

S10 is the newest, and it is the one the live run is actually protected by. It
is deliberately the dullest scenario here -- a hot core, nothing happening, three
hundred seconds of nothing happening -- because the live driver s one job is to
keep not pressing, and every failure mode that matters is a press.
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
RECORDER = ROOT / "TRG_original_recorder.luau"
OUT = ROOT / "_driver_states.luau"

HEAD = """--!nocheck
-- GENERATED by _tools/build_driver_test.py -- edit that file, not this one.
--
-- The driveStep body below is EXTRACTED from _tools/TRG_original_recorder.luau,
-- so this harness cannot pass against a version of the function that is not the
-- shipped one. Everything else here is mock: no Roblox API is touched.

local results = {}
local function say(s) results[#results + 1] = tostring(s) end
-- driveStep calls this on every transition. It is part of the mock surface, and
-- leaving it out is not a small omission: the harness would die on the first
-- state change and every scenario would report as a failure of the driver.
local function emitEvt(kind, rest) say('     evt ' .. kind .. ' ' .. tostring(rest)) end

local Config = {
	SampleInterval = 0.25,
	AutoDrive = false,
	DriveArmSeconds = 20,
	DriveHoldSeconds = 60,
	DriveProveSeconds = 40,
	DriveColdSeconds = 30,
	-- Mirrors the shipped default. The driver reads this to decide whether a
	-- shutdown ends the run or whether it goes on to relight the core, so a
	-- harness without it would be testing the other configuration and every
	-- full-flow scenario below would be asserting the wrong ending.
	ShutdownEndsShift = true,
	-- Also mirrors the shipped default, and it is the live one: the operator
	-- presses the shutdown lever himself, so the driver is handed no control.
	-- Scenarios that cover the retained press path opt in explicitly rather than
	-- this being flipped in a shared place, because a scenario that inherited the
	-- press by accident would assert an ending nobody shipped.
	DrivePressControls = false,
}

-- The recorder s readout table, as the driver sees it. Only `shut_down` reads it,
-- and it reads it to answer one question the driver cannot answer itself: did the
-- GAME agree that the shift is over? That is the replacement for the deleted
-- shutdown proof window, so a harness that left this out would leave the
-- replacement untested -- and, worse, would die on a nil index the first time any
-- scenario reached the state that uses it.
--
-- A scenario sets these from inside its own `tempOf`, which the simulator calls
-- once per step before handing the step to driveStep. That is the same order the
-- recorder uses -- readout first, driver second -- so the harness does not need a
-- second hook to model the world.
local last = {}

local pressed, pressedAt, nowT = {}, {}, 0
local function mk(id) return { __id = id, Parent = { GetFullName = function() return 'X.' .. id end } } end
local shutCandidates  = { mk('ShutClickPart'), mk('ShutFallback') }
local startCandidates = { mk('StartClickPart') }
local function pathOf(cd)
	if cd == nil then return 'nil' end
	return cd.Parent:GetFullName()
end
local function press(cd)
	-- One index, computed once. Writing `pressedAt[#pressed + 1]` after the line
	-- above is an off-by-one that leaves pressedAt[1] nil forever, so the first
	-- scenario dies on arithmetic with a nil the moment the core should respond
	-- to the first press -- which is the one press every scenario depends on.
	local n = #pressed + 1
	pressed[n] = cd.__id
	pressedAt[n] = nowT
	return true
end
local drive = {
	on = true, state = 'arming', verdict = 'unsupported',
	holdT = 0, coldT = 0, armT = 0, proofT = 0,
	proofCd = nil, proofRunning = nil, waitingRun = false, waitingCold = false,
	shutIdx = 1, startIdx = 1, shutDone = false, shutSaid = '',
}
local sawDown, flowArmed = false, false
local now, t0 = 0, 0

"""

TAIL = """
-- ========================== THE SIMULATED CORE ============================
-- A model of pollOnce s flow block, so the driver meets the same edges it will
-- meet in the game: a state has to hold three polls to count, and `sawDown`
-- latches. It is a MODEL -- the shipped detector already has three real
-- recordings behind it, and what is under test here is the driver s reaction to
-- those edges, not the edges themselves.
local DEB = 3
local lowRun, lowDown = 0, 0
local function flowStep(tempF)
	local isRunning = tempF ~= nil and tempF >= 5600
	if not flowArmed then
		if isRunning then
			lowRun = lowRun + 1
			if lowRun >= DEB then flowArmed = true end
		else
			lowRun = 0
		end
	elseif isRunning then
		lowDown = 0
	elseif not sawDown then
		lowDown = lowDown + 1
		if lowDown >= DEB then sawDown = true end
	end
	return isRunning
end

local function reset()
	pressed, pressedAt = {}, {}
	nowT = 0
	drive.on, drive.state, drive.verdict = true, 'arming', 'unsupported'
	drive.holdT, drive.coldT, drive.armT, drive.proofT = 0, 0, 0, 0
	drive.proofCd = nil
	drive.proofRunning, drive.waitingRun, drive.waitingCold = nil, false, false
	drive.shutIdx, drive.startIdx, drive.shutDone = 1, 1, false
	drive.shutSaid = ''
	sawDown, flowArmed = false, false
	lowRun, lowDown = 0, 0
	last = {}
	-- Reset to the LIVE setting, and the scenario re-applies its own choice
	-- afterwards. Done here rather than only in the Config literal above so that
	-- a scenario which opted into the press path cannot leak it into the next
	-- one -- the leak would be silent, and it would make the live scenarios pass
	-- for the wrong reason.
	Config.DrivePressControls = false
end

-- Runs `seconds` of simulated time in steps of `step` (default
-- Config.SampleInterval), and hands each step to driveStep AS the measured dt.
-- That is not a convenience: it is the contract. The shipped driver takes its
-- step from its caller, so a harness that advanced the clock by one amount while
-- telling the driver another would be testing a function nobody ships.
--
-- `step` is what makes S7 possible. A scenario with a one-second step simulates
-- a loop running four times slower than the configuration assumes, which is the
-- 18:01 situation in miniature.
--
-- `firstStep` is what makes S8 possible, and it models the one poll that has no
-- measured predecessor. The real first poll is the only one carrying the initial
-- readout and lamp sweeps, so it is the only one whose duration nothing bounds --
-- and with a measured dt that duration lands on the arm timer in a single step.
local function simulate(seconds, tempOf, step, firstStep)
	step = step or Config.SampleInterval
	local trace = {}
	local steps = math.floor(seconds / step + 0.5)
	for i = 1, steps do
		local thisStep = step
		if i == 1 and firstStep ~= nil then thisStep = firstStep end
		nowT = nowT + thisStep
		now = nowT
		local tempF = tempOf(nowT)
		local isRunning = flowStep(tempF)
		local before = drive.state
		driveStep(tempF, isRunning, thisStep)
		if drive.state ~= before then
			trace[#trace + 1] = string.format('%.2f  %s -> %s', nowT, before, drive.state)
		end
	end
	return trace
end

local function join(t)
	if #t == 0 then return '(none)' end
	return table.concat(t, '; ')
end

local function pressedList()
	if #pressed == 0 then return '(nothing pressed)' end
	return table.concat(pressed, ', ')
end

-- The clock at which press N happened, so a scenario s temperature can respond
-- to it. nil when that press has not happened yet.
local function sincePress(n)
	if pressedAt[n] == nil then return nil end
	return nowT - pressedAt[n]
end

-- `step` and `firstPress` are optional and exist for S7. `firstPress` is a
-- {lo, hi} window on the simulated time of the FIRST press, which is the only
-- assertion that can tell a driver which measures its step from one which
-- assumes it: the press happens either way, and only its timing differs.
local function scenario(name, seconds, tempOf, expectPresses, expectState, step, firstPress, firstStep, opts)
	reset()
	local firstResult = #results + 1
	-- The configuration this scenario runs under, applied AFTER reset (which
	-- restores the live default) and before the first step. Named rather than
	-- positional in the hope that a reader can tell at a glance which of the two
	-- answers to "who presses" a given scenario is asserting.
	opts = opts or {}
	Config.DrivePressControls = opts.pressControls == true
	local trace = simulate(seconds, tempOf, step, firstStep)
	local ok = true
	local notes = {}
	if pressedList() ~= expectPresses then
		ok = false
		notes[#notes + 1] = 'pressed [' .. pressedList() .. '] wanted [' .. expectPresses .. ']'
	end
	if drive.state ~= expectState then
		ok = false
		notes[#notes + 1] = 'state ' .. drive.state .. ' wanted ' .. expectState
	end
	-- The verdict and the confirmation count, both optional, both asked for only
	-- by the scenarios that need them. The verdict is how the two ways into
	-- `shut_down` stay told apart -- a state assertion cannot see the difference
	-- between a press this driver made and one the operator made, and that
	-- difference is the whole subject of the live run.
	if opts.verdict ~= nil and drive.verdict ~= opts.verdict then
		ok = false
		notes[#notes + 1] = 'verdict ' .. drive.verdict .. ' wanted ' .. opts.verdict
	end
	local confirms = nil
	if opts.confirms ~= nil then
		confirms = 0
		for i = firstResult, #results do
			if string.find(results[i], 'the game confirms', 1, true) ~= nil then
				confirms = confirms + 1
			end
		end
		if confirms ~= opts.confirms then
			ok = false
			notes[#notes + 1] = 'the confirmation was written ' .. confirms ..
				' times, wanted exactly ' .. tostring(opts.confirms)
		end
	end
	if firstPress ~= nil then
		local at = pressedAt[1]
		if at == nil then
			ok = false
			notes[#notes + 1] = 'no first press, wanted one at ' ..
				string.format('%.1f..%.1f', firstPress[1], firstPress[2])
		elseif at < firstPress[1] or at > firstPress[2] then
			ok = false
			notes[#notes + 1] = string.format(
				'first press at %.2f, wanted %.1f..%.1f -- a driver using the configured '
				.. 'poll period would press at %.1f', at,
				firstPress[1], firstPress[2],
				Config.DriveArmSeconds + Config.DriveHoldSeconds
					/ Config.SampleInterval * (step or Config.SampleInterval))
		end
	end
	say((ok and 'PASS ' or 'FAIL ') .. name)
	say('     pressed ' .. pressedList())
	say('     state   ' .. drive.state .. '  verdict ' .. drive.verdict)
	if confirms ~= nil then say('     confirms ' .. tostring(confirms)) end
	say('     trace   ' .. join(trace))
	if not ok then
		for _, n in ipairs(notes) do say('     !! ' .. n) end
	end
	say('')
end

-- ========================== S1 ============================================
-- Injected on a hot core, which is where the operator arms the driver: he
-- starts the core himself and presses DRIVER once it is up. The driver holds,
-- presses shut, and STOPS there -- in the same poll, without waiting to watch
-- the core come down. A shutdown ends the shift, so there is nothing left to
-- relight and nothing left to record; `shut_down` is a state with no press in
-- it, and the recorder s end-of-shift rule is what seals the file.
--
-- The falling temperature in this scenario is therefore decoration now: the
-- driver no longer reads it. It is left in place because a plant that stays hot
-- after a shutdown is a real case -- S2 is that case -- and because the two
-- scenarios together pin that the ending does not depend on the cooling.
scenario('S1 hot core, driver holds the controls', 300, function(t)
	local n = #pressed
	if n == 0 then return 22000 end
	local since = sincePress(n)
	return math.max(800, 22000 - since * 400)
end, 'ShutClickPart', 'shut_down', nil, nil, nil, { pressControls = true })

-- ========================== S2 ============================================
-- Injected on a hot core, and the temperature NEVER MOVES afterwards: the plant
-- ignores the switch completely.
--
-- This scenario used to assert `inert`. The driver was supposed to watch for the
-- temperature to fall, and to name the control when it did not. That assertion is
-- gone, and it is worth being exact about why it is not a loss of coverage.
--
-- The operator says the lever shuts the core down AT ONCE, so a fall in the
-- monitor temperature is not evidence about the press. The 18:35 run is the
-- measurement that settles it: that run s own `shut accepted after 8.7s` was
-- produced by a 431 F move, and m.fluct in the same file has p5 = -218 F and
-- p95 = +253 F with extremes past -1700. The move was inside the plant s
-- ordinary wobble, and the core had not gone down at all -- s.GameActive stayed
-- true for another 414 seconds and the temperature ROSE in the meantime.
--
-- What is asserted instead is the claim that was always the real one: exactly
-- ONE press, `ShutFallback` never touched, and the driver stops. A core that
-- ignores the switch cannot be told from one that obeys it at the moment of the
-- press -- so the driver does not try, and S9 is where the difference is named,
-- by the game s own statement rather than by a sensor.
scenario('S2 hot core, the plant ignores the press', 300, function() return 22000 end,
	'ShutClickPart', 'shut_down', nil, nil, nil, { pressControls = true })

-- ========================== S3 ============================================
-- Injected on a COLD core, which is how every shift now BEGINS.
--
-- THE OPERATOR REVERSED THIS ASSERTION, SO THE TEST MOVED WITH IT. It used to
-- require the driver to press nothing and report `cold-at-inject`, on the
-- argument that the one-shot rule reserved the startup for the end of the flow.
-- The answer is that the DRIVER BUTTON is the authorisation: pressing it is a
-- person deciding that this attempt is the one to spend, and a driver that then
-- declines to act has spent the attempt on nothing.
--
-- Written as a full-flow assertion rather than as "it presses StartClickPart",
-- because the interesting claim is not the first press but where the run ENDS.
-- A driver that lights the core and then sits in `waiting_up` forever, waiting
-- for a down-then-up that this configuration never performs, would pass the weak
-- version of this test.
--
-- The first press lands at the END of the arm window rather than before it: the
-- arm timer is what distinguishes "the core is cold" from "the readout has not
-- arrived yet", and S4 pins the other side of that.
scenario('S3 cold core is lit by the driver', 400, function(t)
	local n = #pressed
	if n == 0 then return 900 end
	local since = sincePress(n)
	if n == 1 then return math.min(22000, 900 + since * 2000) end
	return math.max(800, 22000 - since * 400)
end, 'StartClickPart, ShutClickPart', 'shut_down', nil, nil, nil, { pressControls = true })

-- ========================== S4 ============================================
-- No temperature readout at all. `isRunning` is false whenever the readout is
-- missing, exactly as it is when the core is off -- so this is the scenario
-- that catches a driver which reads a dead sensor as a dead reactor and starts
-- pressing switches on a plant it cannot see.
scenario('S4 no readout', 200, function() return nil end,
	'(nothing pressed)', 'arming')

-- ========================== S5 ============================================
-- The operator's own sequence, LIVE: the core is cold at inject, and the human
-- lights it BY HAND -- here a hundred seconds later, which is deliberately well
-- past the twenty-second arm window.
--
-- Lighting it INSIDE the window is the easy case and no longer the interesting
-- one. Past the window the driver has already decided the core was cold, and
-- that decision used to be the end of the matter: the old driver answered it by
-- pressing START, and under `D7` it is not allowed to. So what this asserts is
-- that the cold verdict is a REPORT and not a verdict -- nothing is pressed, the
-- state stays `arming`, and the operator's own startup carries it into
-- `watching` exactly as it would have if he had been quicker.
--
-- `waitingCold` is the latch that makes that wait say its piece once. A driver
-- that announced it every poll would pass every assertion here and still be
-- unusable, which is why the flag exists rather than the message being
-- unconditional.
scenario('S5 cold at inject, the operator lights it late', 400, function(t)
	return t < 120 and 900 or 22000
end, '(nothing pressed)', 'watching', nil, nil, nil, { verdict = 'watching' })

-- ========================== S6 ============================================
-- The 18:01 capture, reproduced. The core is running at inject, then goes down
-- ON ITS OWN before the hold expires, and comes back on its own later. The
-- driver must press NOTHING while it is down -- and must not credit itself with
-- the recovery. It presses once the core is running again, and only then.
--
-- Without the proofRunning gate this scenario fails in the specific way the
-- real run failed: the press goes out during the downtime and `not isRunning`
-- accepts it on the first poll, reporting a shutdown the driver did not cause.
scenario('S6 core dips on its own during the hold', 400, function(t)
	local n = #pressed
	if n == 0 then
		if t < 5 then return 22000 end
		if t < 80 then return 3000 end
		return 22000
	end
	local since = sincePress(n)
	return math.max(800, 22000 - since * 400)
end, 'ShutClickPart', 'shut_down', nil, nil, nil, { pressControls = true })

-- ========================== S7 ============================================
-- The 18:01 defect, reproduced. The loop runs at ONE SECOND per poll while the
-- configuration still says 0.25, which is what the real client did -- 283
-- samples over 83.78 s is 3.38 Hz against a configured four.
--
-- The assertion is not that the flow completes, because it completes either way.
-- It is WHEN the shut press lands. Measured, the hold expires 60 s after arming
-- and the press follows within a poll. Assumed, the driver counts 240 polls of
-- its own arithmetic and presses four times too late -- which is precisely the
-- 60-versus-70.59 gap the live run showed, blown up until it cannot be mistaken
-- for slack in the scenario.
scenario('S7 a slow loop is measured, not assumed', 400, function(t)
	local n = #pressed
	if n == 0 then return 22000 end
	local since = sincePress(n)
	return math.max(800, 22000 - since * 400)
end, 'ShutClickPart', 'shut_down', 1.0, { 55, 70 }, nil, { pressControls = true })

-- ========================== S8 ============================================
-- The first poll takes thirty seconds, and the core is running the whole time.
--
-- This is the one poll with no measured predecessor: it is the only one carrying
-- the initial readout discovery and lamp sweeps, so nothing bounds it, and with a
-- measured dt its whole duration lands on the arm timer in a SINGLE step. The
-- debounce needs three polls to confirm the core is running, so the arm window
-- can expire while the core reads perfectly healthy -- and the driver then
-- reports `cold-at-inject` and goes inert on a live reactor, on the one attempt
-- that was available.
--
-- The assertion is that it arms instead. It is worth more than S7 in one respect:
-- S7 catches a driver that under-counts time, which is a wrong number in a file.
-- S8 catches a driver that refuses to act, which is the attempt spent.
scenario('S8 a slow FIRST poll does not fake a cold core', 300, function(t)
	local n = #pressed
	-- The core has to RESPOND to the press, or the shut is inert for a reason
	-- that has nothing to do with the arm window and the scenario would be
	-- asserting on the wrong ending. First written without this, S8 failed with
	-- `shut-inert` -- which is the correct behaviour for a core that ignores the
	-- switch, and says nothing at all about the thing under test.
	if n == 0 then return 22000 end
	local since = sincePress(n)
	return math.max(800, 22000 - since * 400)
end, 'ShutClickPart', 'shut_down', nil, nil, 30, { pressControls = true })

-- ========================== S9 ============================================-- ========================== S9 ============================================
-- The operator presses, and the GAME then says the shift is over.
--
-- This is the live path end to end, and it is the scenario the whole `D7` change
-- was for. The driver presses nothing. It sits in `watching`, the operator s
-- press puts the shutdown screen up, and the driver names both the press and the
-- game s answer to it.
--
-- The evidence for the press is `v.shutdown`, which is the signal the operator
-- named for it (`B3`: pressing the shutdown lever shows
-- `MonitorUI.ShutdownFrame`). That is a screen appearing in the same second as
-- the press rather than an inference from the temperature, and it is the closest
-- thing to a direct read of the press that does not depend on a click line
-- arriving.
--
-- TWO SIGNALS ARRIVE, AND BOTH ARE WORTH A LINE: the shutdown screen goes up with
-- the press at t=100, and the game s own `s.GameActive` goes false at t=150. The
-- first ends `watching`; the second is the machine formally closing the shift,
-- which is the thing that arrives 414 seconds late in the 18:35 capture and is
-- therefore the single most valuable arrival in the whole run. So `confirms = 1`
-- counts the SECOND one -- and it is also the latch assertion, because a
-- confirmation that was not latched would be written on every poll after t=150
-- as well. That is the failure mode that makes a log useless rather than wrong,
-- and the one no state assertion can see.
--
-- THE VERDICT STAYS `user-shut`, and this is the assertion that pins it. The
-- first cut of the shipped code re-confirmed the operator s own press one poll
-- after `watching` ended and overwrote the verdict with `shut-confirmed` -- so
-- the receipt said "the executor s press landed" about a run in which the
-- executor never pressed. Every state assertion still passed; only the verdict
-- could see it.
--
-- `s.GameActive` is set from inside `tempOf`, which the simulator calls once per
-- step before handing the step to driveStep. That is the order the recorder reads
-- the world in, so the harness does not need a second hook to model it.
scenario('S9 the operator presses and the game confirms', 300, function(t)
	if t > 150 then last['s.GameActive'] = false end
	if t > 100 then last['v.shutdown'] = true end
	return 22000
end, '(nothing pressed)', 'shut_down', nil, nil, nil,
	{ verdict = 'user-shut', confirms = 1 })

-- ========================== S10 ===========================================
-- A hot core at inject and NOTHING EVER HAPPENS. Three hundred seconds of a
-- healthy reactor, no press by anyone, and the driver must still be sitting
-- there watching at the end of it.
--
-- This is the dullest scenario in the file and the most important one for the
-- live run, because the live driver s entire correctness is a negative: it must
-- not press. Every way that goes wrong -- arming on a running core and being
-- tempted to switch it off, getting bored during the arm window, treating the
-- absence of an end signal as permission to act -- ends in a press, and this is
-- the scenario that fails when one appears. The arm window expiring is
-- deliberate: the driver has watched the core run past the point where a cold
-- core would have been declared, and that must change nothing.
scenario('S10 hot core, no press from anyone', 300, function() return 22000 end,
	'(nothing pressed)', 'watching', nil, nil, nil, { verdict = 'watching' })

-- ========================== S11 ===========================================
-- The MACHINE ROOM melts down, and the driver names it as exactly that.
--
-- `D9`: `MainframeMeltdown` is the machine room, not the core, and this file used
-- to label it `meltdown (over 39000 F)`. The live driver reaches `shut_down` on
-- it like any other end of shift -- the machine room melting down IS the shift
-- ending from the operator s chair -- and the distinction survives in the message
-- the event carries, which is what a receipt is read for.
--
-- ONE SIGNAL, SO ONE LINE, AND NO CONFIRMATION. This flag is the only end signal
-- in the scenario, so it is the one that ends `watching` -- and `shut_down` then
-- finds the same flag and must recognise it as already written down rather than
-- reporting the machine s meltdown back to itself as a fresh confirmation. A
-- `confirms` of 0 is the assertion for that; it is the mirror image of S9, which
-- has a second signal to report. The two together are what pin that the guard is
-- "is this news" and not merely "is something set".
--
-- The temperature never moves. That is the point: this flag is not a temperature
-- rule, and a driver that inferred a core meltdown from it would be reading
-- 13000 F -- the value the flag actually fired at in the 18:35 capture -- as a
-- catastrophe.
scenario('S11 the machine room melts down', 300, function(t)
	if t > 60 then last['s.MainframeMeltdown'] = true end
	return 22000
end, '(nothing pressed)', 'shut_down', nil, nil, nil,
	{ verdict = 'user-shut', confirms = 0 })

-- Returned, not printed: this runs through an executor-tool boundary that shows
-- the chunk s return value and not necessarily its console, and a test whose
-- output nobody sees is a test nobody ran.
local report = table.concat(results, string.char(10))

-- And an exit code, so a caller can gate on it instead of reading the page. The
-- FAIL is what the scenario helper writes above; `io` and `os.exit` are absent in
-- Studio s Luau and present in the standalone interpreter, so this is guarded
-- rather than unconditional -- a harness that dies on its own failure path with
-- "attempt to index nil" reports the wrong reason for the right result.
if string.find(report, 'FAIL', 1, true) ~= nil and io ~= nil and io.stderr ~= nil then
	io.stderr:write(report .. string.char(10))
	os.exit(1)
end
return report
"""


def extract(path: Path) -> str:
    src = path.read_text(encoding="utf-8")
    m = re.search(r"^local function driveStep\(tempF, isRunning, dt\)\n.*?^end$", src, re.S | re.M)
    if not m:
        sys.exit("could not find driveStep in %s -- did it get renamed, or did its "
                 "signature change? The regex is anchored on `(tempF, isRunning, dt)` "
                 "on purpose: the third parameter is the measured step, and a copy "
                 "of this function without it is the version that ran 18 per cent "
                 "long." % path)
    body = m.group(0)
    # The extraction is only trustworthy if it is complete. A brace/paren count
    # is not a parser, but it fails loudly on the one mistake that matters here:
    # a truncated body that still compiles because the tail happened to close it.
    for open_c, close_c in (("(", ")"), ("{", "}")):
        if body.count(open_c) != body.count(close_c):
            sys.exit("extracted driveStep is unbalanced on %r: %d vs %d"
                     % (open_c, body.count(open_c), body.count(close_c)))
    if not body.rstrip().endswith("end"):
        sys.exit("extracted driveStep does not end in `end`")
    return body


def main() -> int:
    body = extract(RECORDER)
    OUT.write_text(HEAD + body + "\n" + TAIL, encoding="utf-8", newline="\n")
    raw = OUT.read_bytes()
    text = raw.decode("utf-8")
    print("wrote %s" % OUT)
    print("  lines %d  bytes %d  driveStep lines %d"
          % (text.count("\n"), len(raw), body.count("\n") + 1))
    print("  backslash bytes %d  (must be 0: the editor decodes escapes once)"
          % raw.count(0x5C))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
